import QRCode from 'qrcode';
import JsBarcode from 'jsbarcode';
import {levelColor,code} from './model.js';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cache=new Map();
export async function componentContent(c,r){if(c.type==='qr'){const key=code(r);if(!cache.has(key))cache.set(key,QRCode.toString(key,{type:'svg',margin:4,errorCorrectionLevel:'M',color:{dark:'#000000',light:'#ffffff'}}));return await cache.get(key);}if(c.type==='barcode'){const el=document.createElementNS('http://www.w3.org/2000/svg','svg');JsBarcode(el,code(r),{format:'CODE128',displayValue:false,margin:12,height:70});return el.outerHTML;}if(c.type==='rect'||c.type==='color')return '';if(c.type==='arrow')return `<span class="arrow">${c.auto?(r.LEVEL==='1'?'↓':'↑'):esc(c.direction)}</span>`;return `<small>${esc(c.type)}</small><strong>${esc(r[c.type]??code(r))}</strong>`;}
function fitSize(c,text){const value=String(text??'');return Math.max(8,Math.min(c.size,c.w/(Math.max(value.length,1)*.62),c.h*.48));}
async function labelInner(s,r){const pieces=[];for(const c of s.components){let inner=await componentContent(c,r);const fill=c.type==='color'?(c.auto?levelColor(r.LEVEL):c.fg):c.type==='rect'?c.fg:c.bg;pieces.push(`<g transform="translate(${c.x} ${c.y})"><rect width="${c.w}" height="${c.h}" fill="${fill==='transparent'?'none':esc(fill)}"/>`);if(c.type==='qr'||c.type==='barcode'){inner=inner.replace(/<svg[^>]*>/,m=>m.replace(/width="[^"]*"|height="[^"]*"/g,'').replace('<svg',`<svg width="${c.w}" height="${c.h}"`));pieces.push(inner);}else if(c.type==='arrow')pieces.push(`<text x="${c.w/2}" y="${c.h*.78}" text-anchor="middle" font-family="Arial,sans-serif" font-size="${fitSize(c,c.direction)}" fill="${esc(c.fg)}">${c.auto?(r.LEVEL==='1'?'↓':'↑'):esc(c.direction)}</text>`);else if(!['rect','color'].includes(c.type)){const value=r[c.type]??code(r),size=fitSize(c,value);pieces.push(`<text x="${c.w/2}" y="22" text-anchor="middle" font-family="Arial,sans-serif" font-size="${Math.min(14,c.w/6)}" fill="${esc(c.fg)}">${esc(c.type)}</text><text x="${c.w/2}" y="${c.h*.74}" text-anchor="middle" font-family="Arial,sans-serif" font-weight="bold" font-size="${size}" fill="${esc(c.fg)}">${esc(value)}</text>`);}pieces.push('</g>');}return `${s.template?`<image href="${s.template}" width="100%" height="100%" preserveAspectRatio="none"/>`:''}${pieces.join('')}`;}
export async function labelSVG(s,r){return `<svg xmlns="http://www.w3.org/2000/svg" width="${s.width}" height="${s.height}" viewBox="0 0 ${s.width} ${s.height}"><rect width="100%" height="100%" fill="white"/>${await labelInner(s,r)}</svg>`;}
export async function groupedLabelSVG(s,records,orientation='vertical'){const vertical=orientation==='vertical',n=records.length,w=vertical?s.width:s.width*n,h=vertical?s.height*n:s.height;const body=[];for(let i=0;i<n;i++){const r=vertical?records[n-1-i]:records[i];body.push(`<g transform="${vertical?`translate(0 ${i*s.height})`:`translate(${i*s.width} 0)`}">${await labelInner(s,r)}</g>`);}return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="100%" height="100%" fill="white"/>${body.join('')}</svg>`;}
export async function png(s,r){const svg=await labelSVG(s,r);const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=s.width*2;canvas.height=s.height*2;canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return await new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('สร้าง PNG ไม่สำเร็จ')),'image/png'));}finally{URL.revokeObjectURL(url);}}
