import './style.css';import './enhancements.css';
import * as XLSX from 'xlsx';import JSZip from 'jszip';
import {defaultState,defaultLayout,defaultLabel,locations,normalize,csv,code,levelColor,labelGroups,exampleRows,rotatePoint,isoPoint,gridAtIsoPoint,topPoint,gridAtTopPoint,hasAdjacentPath,placementIdentity,assignSelectionRow,gridLine} from './model.js';
import {esc,labelSVG,png,combinedSVG,pngFromSVG} from './labels.js';

let s=defaultState(),page='rack',tool='select',selectedUnits=[101],selectedLevel=1,selected=3,preview=0,renderToken=0,rackZoom=1,labelZoom=1,rackView='iso',rotation=0,exportDirection='vertical',drawing=false,placementRow=null,placementStart=null,placementLast=null,placementAxis=null;
const $=q=>document.querySelector(q),records=()=>locations(s),unit=()=>s.units.find(u=>u.id===selectedUnits[0]),current=()=>records()[preview]||{PLANT:s.plant,ROW:'A',BAY:'01',LEVEL:'1',SIDE:'L'};
const field=(label,id,value,type='text',extra='')=>`<label>${label}<input id="${id}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const zoomBar=(p,z)=>`<div class="zoom"><button id="${p}-zoom-out">−</button><input id="${p}-zoom" type="range" min="50" max="200" step="10" value="${z*100}"><output>${Math.round(z*100)}%</output><button id="${p}-zoom-in">＋</button><button id="${p}-zoom-fit">พอดี</button></div>`;
function notify(msg){const n=$('#notice');if(n){n.textContent=msg;n.hidden=false;}}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function number(v,min,max){const n=Number(v);if(!Number.isInteger(n)||n<min||n>max)throw Error(`ระบุจำนวนเต็ม ${min}–${max}`);return n;}

function render(){const oldView=$('#rack-viewport'),scroll=oldView?{left:oldView.scrollLeft,top:oldView.scrollTop}:null,count=records().length;$('#app').innerHTML=`<header><a class="brand" href="#"><span class="brand-icon">▥</span><span>RACK<span class="light"> / LABEL STUDIO</span></span></a><div class="header-right"><span class="local">● ทำงานบนเครื่องคุณ</span><button id="load">เปิดงาน JSON</button><button id="save">บันทึกงาน ↓</button></div></header><nav>${[['rack','01','ออกแบบพื้นที่'],['design','02','ออกแบบป้าย'],['export','03','ตรวจสอบ & ส่งออก']].map(([p,n,t])=>`<button data-page="${p}" class="${page===p?'active':''}"><span>${n}</span>${t}</button>`).join('')}<span class="count">${count.toLocaleString()} locations</span></nav><div id="notice" role="status" hidden></div><main>${page==='rack'?rackPage():page==='design'?designPage():exportPage()}</main><input hidden id="file" type="file" accept=".csv,.xlsx,.xls"><input hidden id="project" type="file" accept=".json"><input hidden id="image" type="file" accept="image/png,image/jpeg,image/webp">`;bind();if(page==='design')paintLabel();if(scroll&&page==='rack'){const view=$('#rack-viewport');view.scrollLeft=scroll.left;view.scrollTop=scroll.top;}}

function rackPage(){const u=unit(),multi=selectedUnits.length>1,cap=u?.capacities?.[selectedLevel]??2,scale=Math.max(1,s.gridSize/14)*rackZoom;return `<div class="title"><div><p class="eyebrow">WAREHOUSE BUILDER</p><h1>วาง Rack บนกริด</h1><p>ตำแหน่ง Snap เข้ากึ่งกลาง Tile · ลากเพื่อวาง Rack ต่อเป็น Row เดียวกัน · ลากผ่าน Rack เพื่อเลือกหลาย Unit</p></div><div class="actions"><button id="reset-rack" class="danger">↺ Reset</button><button id="sample">↓ ไฟล์ตัวอย่าง</button><button class="primary" id="import">↑ CSV / Excel</button></div></div><div class="game-layout"><aside class="palette"><p class="eyebrow">BUILD</p>${[['select','↖','เลือก / Multi select','ลากผ่าน Rack ที่ต้องการ'],['rack','▥','Unit Rack','ลากเพื่อดู Preview แล้ววาง'],['path','⌁','ทางเดิน','ลากเพื่อดู Preview แล้ววาง'],['erase','⌫','รื้อถอน','ลากเลือกสีส้มแล้วปล่อยเพื่อลบ']].map(([id,icon,title,sub])=>`<button data-tool="${id}" class="build-card ${tool===id?'selected':''}"><b>${icon}</b><span>${title}<small>${sub}</small></span></button>`).join('')}<hr>${field('Plant','plant',s.plant)}${field('ขนาดกริด','grid-size',s.gridSize,'number','min="8" max="60"')}<p class="hint">ขยายได้ 8–60 tiles ต่อด้าน พื้นที่ใหญ่จะเลื่อนได้และใช้ Zoom ช่วยวาง</p><div class="legend"><span><i class="rack-key"></i>Rack ${s.units.length}</span><span><i class="path-key"></i>ทางเดิน ${s.paths.length}</span><span><i class="invalid-key"></i>ไม่มีทางเดิน</span></div></aside><section class="stage game-stage"><div class="stage-toolbar"><div class="segmented"><button data-rack-view="iso" class="${rackView==='iso'?'active':''}">Isometric</button><button data-rack-view="top" class="${rackView==='top'?'active':''}">Top view</button></div><div class="rotate"><button id="rotate-left">↶</button><span>${rotation*90}°</span><button id="rotate-right">↷</button></div>${zoomBar('rack',rackZoom)}</div><div class="iso-viewport" id="rack-viewport"><div class="iso-scaled" style="width:${scale*100}%">${rackSVG()}</div></div><div class="stage-footer"><span>${selectedUnits.length} Unit selected · Delete เพื่อลบ</span><span>${s.gridSize} × ${s.gridSize} tiles · ${rackView==='iso'?'Isometric':'Top view'} ${rotation*90}°</span></div></section><aside class="inspector"><div class="section-label">${multi?'MULTI RACK CONFIG':'UNIT CONFIG'}</div>${multi?multiPanel():u?singlePanel(u,cap):'<div class="empty-inspector">เลือก Unit หรือลากผ่าน Rack หลายตัวเพื่อเลือกพร้อมกัน</div>'}<hr><p class="hint">Rack สีแดงยังใช้งานไม่ได้จนกว่าจะมีทางเดินติดอย่างน้อยหนึ่งด้าน</p><button class="primary next" data-page="design">ออกแบบป้าย →</button></aside></div>`;}
function singlePanel(u,cap){return `<div class="unit-badge">${esc(u.row)}-${String(u.bay).padStart(2,'0')}</div>${field('Row label','unit-row',u.row)}${field('Bay / Run number','unit-bay',u.bay,'number','min="1" max="999"')}${field('จำนวน Level','unit-levels',u.levels,'number','min="1" max="12"')}<label>Level ที่ตั้งค่า<select id="unit-level">${Array.from({length:u.levels},(_,i)=>`<option value="${i+1}" ${selectedLevel===i+1?'selected':''}>Level ${i+1}</option>`).join('')}</select></label><label>ตำแหน่งต่อ Level<select id="unit-capacity"><option value="2" ${cap===2?'selected':''}>2 ตำแหน่ง (L/R)</option><option value="1" ${cap===1?'selected':''}>1 ตำแหน่ง (S)</option><option value="0" ${cap===0?'selected':''}>ปิด Level</option></select></label><button id="apply-unit-capacity">ใช้กับทุก Level</button><button id="delete-unit" class="danger">รื้อ Unit นี้</button>`;}
function multiPanel(){const items=s.units.filter(u=>selectedUnits.includes(u.id));return `<div class="multi-count">${items.length}<small>Unit Racks</small></div>${field('เปลี่ยนทั้งหมดเป็น Row','multi-row',items[0]?.row??'A')}<p class="hint">เมื่อ Apply ระบบจะเรียงตามตำแหน่งบนกริดและรัน Bay ใหม่ตั้งแต่ 01</p><button id="apply-multi-row" class="primary">Apply Row และ Run Bay ใหม่</button><button id="delete-multi" class="danger">รื้อ Unit ที่เลือกทั้งหมด</button>`;}

function rotateGrid(gx,gy){return rotatePoint(gx,gy,s.gridSize,rotation);}
function project(gx,gy){return rackView==='top'?topPoint(gx,gy,s.gridSize,rotation):isoPoint(gx,gy,s.gridSize,rotation);}
function worldSize(){return rackView==='top'?{w:s.gridSize*42+90,h:s.gridSize*42+90}:{w:s.gridSize*84+140,h:s.gridSize*44+180};}
function rackSVG(){let floor='',paths='',links='',units='';for(let gy=0;gy<s.gridSize;gy++)for(let gx=0;gx<s.gridSize;gx++){const p=project(gx,gy);floor+=rackView==='top'?`<rect class="floor-tile" data-grid="${gx},${gy}" x="${p.x-20}" y="${p.y-20}" width="40" height="40"/>`:`<path class="floor-tile" data-grid="${gx},${gy}" d="M${p.x} ${p.y-22} l42 22 l-42 22 l-42-22z"/>`;}
  for(const t of s.paths){const p=project(t.gx,t.gy);paths+=rackView==='top'?`<rect class="path-tile" data-path="${t.gx},${t.gy}" x="${p.x-20}" y="${p.y-20}" width="40" height="40"/>`:`<path class="path-tile" data-path="${t.gx},${t.gy}" d="M${p.x} ${p.y-22} l42 22 l-42 22 l-42-22z"/>`;}
  const sorted=[...s.units].sort((a,b)=>{const [ax,ay]=rotateGrid(a.gx,a.gy),[bx,by]=rotateGrid(b.gx,b.gy);return ax+ay-bx-by;});for(const a of sorted)for(const b of sorted){if(a.id>=b.id||a.row!==b.row||Math.abs(a.gx-b.gx)+Math.abs(a.gy-b.gy)!==1)continue;const p=project(a.gx,a.gy),q=project(b.gx,b.gy);links+=`<path class="row-link" d="M${p.x} ${p.y} L${q.x} ${q.y}"/>`;}
  for(const u of sorted){const p=project(u.gx,u.gy),active=selectedUnits.includes(u.id),invalid=!hasAdjacentPath(u,s.paths),classes=`${active?'active':''} ${invalid?'invalid':''}`;if(rackView==='top'){units+=`<g class="unit-rack top-unit ${classes}" data-unit="${u.id}"><rect x="${p.x-18}" y="${p.y-18}" width="36" height="36" rx="3"/><text x="${p.x}" y="${p.y+4}" text-anchor="middle">${esc(u.row)}-${String(u.bay).padStart(2,'0')}</text></g>`;continue;}const h=34+u.levels*10;units+=`<g class="unit-rack ${classes}" data-unit="${u.id}"><path class="unit-top" d="M${p.x} ${p.y-h} l42 22 l-42 22 l-42-22z"/><path class="unit-left" d="M${p.x-42} ${p.y-h+22} l42 22 v${h-22} l-42-22z"/><path class="unit-right" d="M${p.x+42} ${p.y-h+22} l-42 22 v${h-22} l42-22z"/><text x="${p.x}" y="${p.y-h+26}" text-anchor="middle">${esc(u.row)}-${String(u.bay).padStart(2,'0')}</text></g>`;}const z=worldSize();return `<svg id="rack-svg" viewBox="0 0 ${z.w} ${z.h}" xmlns="http://www.w3.org/2000/svg">${floor}${paths}${links}${units}<g id="build-preview" pointer-events="none"></g><rect id="selection-box" class="selection-box" visibility="hidden"/></svg>`;}

function designPage(){const c=s.components.find(x=>x.id===selected);return `<div class="title"><div><p class="eyebrow">LABEL DESIGNER</p><h1>ออกแบบป้าย Location</h1><p>Preview และ Export ใช้ SVG renderer เดียวกัน</p></div><div class="actions"><button id="reset-label" class="danger">↺ Reset</button><button id="upload-template">↑ Upload Template</button></div></div><div class="upload-help"><b>ภาพ Template:</b> PNG, JPG/JPEG หรือ WebP · ไม่เกิน 10 MB</div><div class="workspace"><aside><h3>องค์ประกอบ</h3><div class="components">${['color','rect','arrow','qr','barcode','PLANT','ROW','BAY','LEVEL','SIDE','LOCATION'].map(t=>`<button data-add="${t}">＋ ${{color:'สีตามชั้น',rect:'Rectangle',arrow:'ลูกศร',qr:'QR code',barcode:'Barcode'}[t]||t}</button>`).join('')}</div><div class="two">${field('กว้าง','width',s.width,'number')}${field('สูง','height',s.height,'number')}</div>${s.template?'<button id="remove-template">ลบ Template</button>':''}<h3>Layers</h3><div class="layers">${[...s.components].reverse().map(x=>`<button data-layer="${x.id}" class="${x.id===selected?'selected':''}">${esc(x.type)} <span>#${x.id}</span></button>`).join('')}</div></aside><section class="stage"><div class="stage-toolbar"><strong>Label canvas</strong>${zoomBar('label',labelZoom)}</div><div class="designer-area label-viewport"><div id="canvas" style="aspect-ratio:${s.width}/${s.height};width:${labelZoom*100}%"></div></div><div class="stage-footer"><button id="prev">←</button><code>${esc(code(current()))}</code><button id="next">→</button></div></section><aside><h3>${c?esc(c.type):'เลือกองค์ประกอบ'}</h3>${componentPanel(c)}<hr><button id="svg">ดาวน์โหลด SVG</button><button id="png">ดาวน์โหลด PNG</button><button class="primary next" data-page="export">ตรวจสอบ & ส่งออก →</button></aside></div>`;}
function componentPanel(c){if(!c)return '';return `<div class="two">${field('X','cx',c.x,'number')}${field('Y','cy',c.y,'number')}${field('กว้าง','cw',c.w,'number')}${field('สูง','ch',c.h,'number')}</div>${field('สี','fg',c.fg,'color')}${field('Background','bg',c.bg==='transparent'?'#ffffff':c.bg,'color')}<label class="check"><input id="transparent" type="checkbox" ${c.bg==='transparent'?'checked':''}> โปร่งใส</label>${field('ขนาดตัวอักษรสูงสุด','font-size',c.size,'number')}${['color','arrow'].includes(c.type)?`<label class="check"><input id="auto" type="checkbox" ${c.auto?'checked':''}> อัตโนมัติตาม Level</label>`:''}<div class="two"><button id="forward">ขึ้นหน้า ↑</button><button id="backward">ลงหลัง ↓</button></div><button id="delete-component" class="danger">ลบ</button>`;}
function exportPage(){const rr=records(),groups=labelGroups(rr);return `<div class="title"><div><p class="eyebrow">READY TO LABEL</p><h1>ตรวจตำแหน่ง</h1><p>${rr.length} ป้าย · ${groups.length} กลุ่ม</p></div><div class="actions"><button id="csv">↓ CSV</button><button id="xlsx">↓ Excel</button><button id="zip">↓ PNG</button><button id="print">พิมพ์ / PDF</button></div></div><section class="export-options"><div><h3>รวม Level เป็นป้ายใหญ่</h3><p>รวม Plant, Row, Bay และ Side เดียวกัน</p></div><label>ทิศทาง<select id="export-direction"><option value="vertical">แนวตั้ง</option><option value="horizontal" ${exportDirection==='horizontal'?'selected':''}>แนวนอน</option></select></label><button class="primary" id="combined-zip">↓ ป้ายรวม ZIP</button></section><section class="table-panel"><table><thead><tr>${['PLANT','ROW','BAY','LEVEL','SIDE','LOCATION CODE'].map(t=>`<th>${t}</th>`).join('')}</tr></thead><tbody>${rr.slice(0,500).map(r=>`<tr><td>${esc(r.PLANT)}</td><td>${esc(r.ROW)}</td><td>${r.BAY}</td><td><span class="level-dot" style="background:${levelColor(r.LEVEL)}"></span>${r.LEVEL}</td><td>${r.SIDE}</td><td><code>${esc(code(r))}</code></td></tr>`).join('')}</tbody></table></section>`;}

async function paintLabel(){const token=++renderToken,canvas=$('#canvas');if(!canvas)return;canvas.innerHTML=await labelSVG(s,current());if(token!==renderToken)return;for(const c of s.components){const el=document.createElement('div');el.className='overlay hitbox'+(c.id===selected?' chosen':'');el.dataset.component=c.id;el.style.cssText=`left:${c.x/s.width*100}%;top:${c.y/s.height*100}%;width:${c.w/s.width*100}%;height:${c.h/s.height*100}%`;el.innerHTML=c.id===selected?'<span class="resize"></span>':'';canvas.appendChild(el);}canvas.onpointerdown=dragComponent;}
function on(id,event,fn){const el=$('#'+id);if(el)el.addEventListener(event,async e=>{try{await fn(e);}catch(err){notify(err.message);}});}const mutate=fn=>{fn();render();};
function bind(){document.querySelectorAll('[data-page]').forEach(e=>e.onclick=()=>{page=e.dataset.page;render();});document.querySelectorAll('[data-tool]').forEach(e=>e.onclick=()=>{tool=e.dataset.tool;render();});document.querySelectorAll('[data-rack-view]').forEach(e=>e.onclick=()=>{rackView=e.dataset.rackView;render();});on('rotate-left','click',()=>{rotation=(rotation+3)%4;render();});on('rotate-right','click',()=>{rotation=(rotation+1)%4;render();});on('plant','change',e=>mutate(()=>s.plant=e.target.value.trim().toUpperCase()));on('grid-size','change',e=>mutate(()=>resizeGrid(number(e.target.value,8,60))));on('rack-svg','pointerdown',rackPointerDown);bindZoom('rack',()=>rackZoom,v=>rackZoom=v);bindZoom('label',()=>labelZoom,v=>labelZoom=v);bindReset();bindUnit();bindFiles();bindLabel();bindExport();bindKeys();}
function bindKeys(){document.onkeydown=e=>{const target=e.target;if(e.key==='Delete'&&page==='rack'&&selectedUnits.length&&!['INPUT','TEXTAREA','SELECT'].includes(target?.tagName)&&!target?.isContentEditable){e.preventDefault();removeSelected();}};}
function bindZoom(p,get,set){on(`${p}-zoom`,'input',e=>{set(Number(e.target.value)/100);render();});on(`${p}-zoom-out`,'click',()=>{set(Math.max(.5,get()-.1));render();});on(`${p}-zoom-in`,'click',()=>{set(Math.min(2,get()+.1));render();});on(`${p}-zoom-fit`,'click',()=>{set(1);render();});}
function bindReset(){on('reset-rack','click',()=>{if(confirm('ล้างผัง Rack และกลับไปแบบเริ่มต้น?'))mutate(()=>{Object.assign(s,defaultLayout());s.imported=null;selectedUnits=[101];tool='select';});});on('reset-label','click',()=>{if(confirm('ล้างป้ายและกลับไปแบบเริ่มต้น?'))mutate(()=>{Object.assign(s,defaultLabel());selected=3;});});}
function bindUnit(){const u=unit();if(u&&selectedUnits.length===1){on('unit-row','change',e=>changeSingle(u,'row',e.target.value.trim().toUpperCase()));on('unit-bay','change',e=>changeSingle(u,'bay',number(e.target.value,1,999)));on('unit-levels','change',e=>mutate(()=>{u.levels=number(e.target.value,1,12);selectedLevel=Math.min(selectedLevel,u.levels);s.imported=null;}));on('unit-level','change',e=>{selectedLevel=Number(e.target.value);render();});on('unit-capacity','change',e=>mutate(()=>{u.capacities[selectedLevel]=Number(e.target.value);s.imported=null;}));on('apply-unit-capacity','click',()=>mutate(()=>{const v=Number($('#unit-capacity').value);for(let l=1;l<=u.levels;l++)u.capacities[l]=v;s.imported=null;}));on('delete-unit','click',()=>removeSelected());}on('apply-multi-row','click',applyMultiRow);on('delete-multi','click',removeSelected);}
function bindFiles(){on('sample','click',()=>download(new Blob([csv(exampleRows)],{type:'text/csv;charset=utf-8'}),'location-import-template.csv'));on('import','click',()=>$('#file').click());on('file','change',importFile);on('save','click',()=>download(new Blob([JSON.stringify(s)],{type:'application/json'}),'rack-project.json'));on('load','click',()=>$('#project').click());on('project','change',loadProject);}
function bindLabel(){on('upload-template','click',()=>$('#image').click());on('image','change',loadImage);on('remove-template','click',()=>mutate(()=>s.template=null));document.querySelectorAll('[data-add]').forEach(e=>e.onclick=()=>mutate(()=>{const id=Date.now();s.components.push({id,type:e.dataset.add,x:30,y:30,w:150,h:120,fg:'#14283f',bg:'transparent',size:38,auto:true,direction:'↑'});selected=id;}));document.querySelectorAll('[data-layer]').forEach(e=>e.onclick=()=>{selected=Number(e.dataset.layer);render();});const c=()=>s.components.find(x=>x.id===selected);for(const [id,key] of [['cx','x'],['cy','y'],['cw','w'],['ch','h'],['font-size','size']])on(id,'change',e=>mutate(()=>c()[key]=number(e.target.value,['x','y'].includes(key)?0:1,2400)));for(const key of ['fg','bg'])on(key,'change',e=>mutate(()=>c()[key]=e.target.value));on('transparent','change',e=>mutate(()=>c().bg=e.target.checked?'transparent':'#ffffff'));on('auto','change',e=>mutate(()=>c().auto=e.target.checked));for(const [id,d] of [['forward',1],['backward',-1]])on(id,'click',()=>mutate(()=>{const i=s.components.indexOf(c()),j=i+d;if(j>=0&&j<s.components.length)[s.components[i],s.components[j]]=[s.components[j],s.components[i]];}));on('delete-component','click',()=>mutate(()=>{s.components=s.components.filter(x=>x.id!==selected);selected=s.components.at(-1)?.id;}));for(const key of ['width','height'])on(key,'change',e=>mutate(()=>s[key]=number(e.target.value,100,2400)));for(const [id,d] of [['prev',-1],['next',1]])on(id,'click',()=>{preview=(preview+d+records().length)%Math.max(1,records().length);render();});on('svg','click',async()=>download(new Blob([await labelSVG(s,current())],{type:'image/svg+xml'}),code(current())+'.svg'));on('png','click',async()=>download(await png(s,current()),code(current())+'.png'));}
function bindExport(){on('csv','click',()=>download(new Blob([csv(records())],{type:'text/csv;charset=utf-8'}),'locations.csv'));on('xlsx','click',exportXlsx);on('zip','click',e=>exportZip(e,false));on('combined-zip','click',e=>exportZip(e,true));on('export-direction','change',e=>exportDirection=e.target.value);on('print','click',printLabels);}

function resizeGrid(size){const occupied=[...s.units,...s.paths],required=Math.max(8,...occupied.map(x=>Math.max(x.gx,x.gy)+1));if(size<required)throw Error(`ลดไม่ได้: มีชิ้นส่วนอยู่ถึง tile ${required} กรุณารื้อหรือย้ายก่อน`);s.gridSize=size;}
function changeSingle(u,key,value){if(key==='row'&&!value)throw Error('Row ห้ามว่าง');const row=key==='row'?value:u.row,bay=key==='bay'?value:u.bay;if(s.units.some(x=>x.id!==u.id&&x.row===row&&x.bay===bay))throw Error(`มี ${row}-${String(bay).padStart(2,'0')} แล้ว`);mutate(()=>{u[key]=value;s.imported=null;});}
function applyMultiRow(){const value=$('#multi-row').value.trim().toUpperCase();if(!value)throw Error('Row ห้ามว่าง');mutate(()=>{assignSelectionRow(s.units,selectedUnits,value);s.imported=null;});}
function removeSelected(){mutate(()=>{s.units=s.units.filter(u=>!selectedUnits.includes(u.id));selectedUnits=[];s.imported=null;});}
function addUnit(g,row){if(!validGrid(g)||s.units.some(u=>u.gx===g.gx&&u.gy===g.gy)||s.paths.some(p=>p.gx===g.gx&&p.gy===g.gy))return null;const identity=placementIdentity(s.units,g,row),u={id:Date.now()+Math.random(),gx:g.gx,gy:g.gy,...identity,levels:3,capacities:{}};s.units.push(u);s.imported=null;return u;}
function pointFromEvent(e){const svg=$('#rack-svg');return new DOMPoint(e.clientX,e.clientY).matrixTransform(svg.getScreenCTM().inverse());}
function gridFromEvent(e){const hit=document.elementFromPoint(e.clientX,e.clientY);const unitEl=hit?.closest?.('[data-unit]');if(unitEl){const u=s.units.find(x=>x.id===Number(unitEl.dataset.unit));if(u)return {gx:u.gx,gy:u.gy};}const pathEl=hit?.closest?.('[data-path]');if(pathEl){const [gx,gy]=pathEl.dataset.path.split(',').map(Number);return {gx,gy};}const tile=hit?.closest?.('[data-grid]');if(tile){const [gx,gy]=tile.dataset.grid.split(',').map(Number);return {gx,gy};}const p=pointFromEvent(e);return rackView==='top'?gridAtTopPoint(p.x,p.y,s.gridSize,rotation):gridAtIsoPoint(p.x,p.y,s.gridSize,rotation);}
const validGrid=g=>g.gx>=0&&g.gx<s.gridSize&&g.gy>=0&&g.gy<s.gridSize;
const gridKey=g=>`${g.gx},${g.gy}`;
const clampGrid=g=>({gx:Math.max(0,Math.min(s.gridSize-1,g.gx)),gy:Math.max(0,Math.min(s.gridSize-1,g.gy))});
const rackAvailable=g=>validGrid(g)&&!s.units.some(u=>u.gx===g.gx&&u.gy===g.gy)&&!s.paths.some(p=>p.gx===g.gx&&p.gy===g.gy);
const pathAvailable=g=>validGrid(g)&&!s.units.some(u=>u.gx===g.gx&&u.gy===g.gy)&&!s.paths.some(p=>p.gx===g.gx&&p.gy===g.gy);
function previewShape(kind,g){const p=project(g.gx,g.gy);if(kind==='path')return rackView==='top'?`<rect class="path-preview" x="${p.x-20}" y="${p.y-20}" width="40" height="40"/>`:`<path class="path-preview" d="M${p.x} ${p.y-22} l42 22 l-42 22 l-42-22z"/>`;if(rackView==='top')return `<g class="rack-preview"><rect x="${p.x-18}" y="${p.y-18}" width="36" height="36" rx="3"/></g>`;const h=64;return `<g class="rack-preview"><path class="unit-top" d="M${p.x} ${p.y-h} l42 22 l-42 22 l-42-22z"/><path class="unit-left" d="M${p.x-42} ${p.y-h+22} l42 22 v${h-22} l-42-22z"/><path class="unit-right" d="M${p.x+42} ${p.y-h+22} l-42 22 v${h-22} l42-22z"/></g>`;}
function showBuildPreview(kind,points){const layer=$('#build-preview');if(layer)layer.innerHTML=points.map(g=>previewShape(kind,g)).join('');}
function applySelectionHighlight(){document.querySelectorAll('[data-unit]').forEach(el=>el.classList.toggle('active',selectedUnits.includes(Number(el.dataset.unit))));}
function applyEraseHighlight(unitIds,pathKeys){document.querySelectorAll('[data-unit]').forEach(el=>el.classList.toggle('erase-preview',unitIds.has(Number(el.dataset.unit))));document.querySelectorAll('[data-path]').forEach(el=>el.classList.toggle('erase-preview',pathKeys.has(el.dataset.path)));}
function rackPointerDown(e){const unitEl=e.target.closest('[data-unit]'),svg=$('#rack-svg'),startPoint=pointFromEvent(e);drawing=true;svg.setPointerCapture(e.pointerId);
  if(tool==='select'){let last=clampGrid(gridFromEvent(e)),brush=!!unitEl;if(brush){const id=Number(unitEl.dataset.unit);selectedUnits=e.ctrlKey||e.metaKey?[...new Set([...selectedUnits,id])]:[id];applySelectionHighlight();}else selectedUnits=[];const box=$('#selection-box');svg.onpointermove=ev=>{if(brush){const target=clampGrid(gridFromEvent(ev));const ids=new Set(selectedUnits);for(const g of gridLine(last,target)){const u=s.units.find(x=>x.gx===g.gx&&x.gy===g.gy);if(u)ids.add(u.id);}selectedUnits=[...ids];last=target;applySelectionHighlight();return;}const p=pointFromEvent(ev),x1=Math.min(startPoint.x,p.x),x2=Math.max(startPoint.x,p.x),y1=Math.min(startPoint.y,p.y),y2=Math.max(startPoint.y,p.y);box.setAttribute('x',x1);box.setAttribute('y',y1);box.setAttribute('width',x2-x1);box.setAttribute('height',y2-y1);box.setAttribute('visibility','visible');selectedUnits=s.units.filter(u=>{const q=project(u.gx,u.gy);return q.x>=x1&&q.x<=x2&&q.y>=y1&&q.y<=y2;}).map(u=>u.id);applySelectionHighlight();};svg.onpointerup=()=>{drawing=false;render();};return;}
  if(tool==='rack'){const existing=unitEl?s.units.find(u=>u.id===Number(unitEl.dataset.unit)):null;placementRow=existing?.row??null;placementStart=existing?{gx:existing.gx,gy:existing.gy}:clampGrid(gridFromEvent(e));placementAxis=null;let planned=existing?[]:[placementStart].filter(rackAvailable);if(existing)selectedUnits=[existing.id];showBuildPreview('rack',planned);const update=ev=>{let target=clampGrid(gridFromEvent(ev));if(!placementAxis&&(target.gx!==placementStart.gx||target.gy!==placementStart.gy))placementAxis=Math.abs(target.gx-placementStart.gx)>=Math.abs(target.gy-placementStart.gy)?'x':'y';if(placementAxis==='x')target={gx:target.gx,gy:placementStart.gy};if(placementAxis==='y')target={gx:placementStart.gx,gy:target.gy};planned=gridLine(placementStart,target).filter(rackAvailable);showBuildPreview('rack',planned);};svg.onpointermove=update;svg.onpointerup=()=>{const ids=existing?[existing.id]:[];for(const g of planned){const added=addUnit(g,placementRow);if(added){placementRow??=added.row;ids.push(added.id);}}selectedUnits=ids;drawing=false;placementRow=null;placementStart=null;placementAxis=null;renumberSelectedRow();render();};return;}
  if(tool==='path'){let last=clampGrid(gridFromEvent(e)),planned=new Map();const collect=points=>{for(const g of points)if(pathAvailable(g))planned.set(gridKey(g),g);showBuildPreview('path',[...planned.values()]);};collect([last]);svg.onpointermove=ev=>{const target=clampGrid(gridFromEvent(ev));collect(gridLine(last,target));last=target;};svg.onpointerup=()=>{for(const g of planned.values())paintPath(g);drawing=false;render();};return;}
  if(tool==='erase'){let last=clampGrid(gridFromEvent(e)),unitIds=new Set(),pathKeys=new Set();const collect=points=>{for(const g of points){const u=s.units.find(x=>x.gx===g.gx&&x.gy===g.gy);if(u)unitIds.add(u.id);if(s.paths.some(x=>x.gx===g.gx&&x.gy===g.gy))pathKeys.add(gridKey(g));}applyEraseHighlight(unitIds,pathKeys);};collect([last]);svg.onpointermove=ev=>{const target=clampGrid(gridFromEvent(ev));collect(gridLine(last,target));last=target;};svg.onpointerup=()=>{s.units=s.units.filter(u=>!unitIds.has(u.id));s.paths=s.paths.filter(p=>!pathKeys.has(gridKey(p)));selectedUnits=selectedUnits.filter(id=>!unitIds.has(id));if(unitIds.size)s.imported=null;drawing=false;render();};return;}
  drawing=false;
}
function renumberSelectedRow(){const items=s.units.filter(u=>selectedUnits.includes(u.id));if(!items.length)return;const row=items[0].row,all=s.units.filter(u=>u.row===row).sort((a,b)=>a.gy-b.gy||a.gx-b.gx);all.forEach((u,i)=>u.bay=i+1);}
function paintPath(g){if(validGrid(g)&&!s.units.some(u=>u.gx===g.gx&&u.gy===g.gy)&&!s.paths.some(p=>p.gx===g.gx&&p.gy===g.gy))s.paths.push(g);}

async function importFile(e){const f=e.target.files[0];if(!f)return;const wb=XLSX.read(await f.arrayBuffer(),{type:'array'});s.imported=normalize(XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:'',raw:false}));page='export';render();}
async function loadProject(e){const p=JSON.parse(await e.target.files[0].text());if(!Array.isArray(p.components))throw Error('ไฟล์งานไม่ถูกต้อง');if(!Array.isArray(p.units))Object.assign(p,defaultLayout());p.version=4;p.gridSize??=14;p.paths??=[];s=p;selectedUnits=s.units[0]?[s.units[0].id]:[];render();}
async function loadImage(e){const f=e.target.files[0];if(!f)return;if(f.size>10*1024*1024)throw Error('ภาพต้องไม่เกิน 10 MB');const u=URL.createObjectURL(f);try{const img=new Image();img.src=u;await img.decode();const c=document.createElement('canvas'),scale=Math.min(1,2000/img.width);c.width=img.width*scale;c.height=img.height*scale;c.getContext('2d').drawImage(img,0,0,c.width,c.height);s.template=c.toDataURL('image/png');render();}finally{URL.revokeObjectURL(u);}}
function exportXlsx(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(records().map(r=>({...r,Location_Code:code(r)}))),'Locations');XLSX.writeFile(wb,'locations.xlsx');}
async function exportZip(e,combined){e.target.disabled=true;try{const zip=new JSZip();if(combined){for(const g of labelGroups(records())){const c=await combinedSVG(s,g.items,exportDirection);zip.file(`${g.key}_${exportDirection}.png`,await pngFromSVG(c.svg,c.width,c.height));}}else for(const r of records())zip.file(code(r)+'.png',await png(s,r));download(await zip.generateAsync({type:'blob'}),combined?`rack-labels-combined-${exportDirection}.zip`:'rack-labels.zip');}finally{e.target.disabled=false;}}
async function printLabels(){const labels=await Promise.all(records().map(r=>labelSVG(s,r))),frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:0;height:0;border:0';document.body.append(frame);frame.contentDocument.write(`<style>@page{size:A4;margin:10mm}svg{display:block;width:190mm;height:auto;break-inside:avoid;margin-bottom:4mm}</style>${labels.join('')}`);frame.contentDocument.close();frame.contentWindow.onafterprint=()=>frame.remove();frame.contentWindow.print();}
function dragComponent(e){const el=e.target.closest('[data-component]');if(!el)return;e.preventDefault();const c=s.components.find(x=>x.id===Number(el.dataset.component)),resize=e.target.classList.contains('resize'),bounds=$('#canvas').getBoundingClientRect(),x=e.clientX,y=e.clientY,o={...c};selected=c.id;el.setPointerCapture(e.pointerId);el.onpointermove=ev=>{const dx=(ev.clientX-x)/bounds.width*s.width,dy=(ev.clientY-y)/bounds.height*s.height;if(resize){c.w=Math.max(20,Math.round(o.w+dx));c.h=Math.max(20,Math.round(o.h+dy));}else{c.x=Math.round(o.x+dx);c.y=Math.round(o.y+dy);}el.style.left=c.x/s.width*100+'%';el.style.top=c.y/s.height*100+'%';el.style.width=c.w/s.width*100+'%';el.style.height=c.h/s.height*100+'%';};el.onpointerup=()=>render();}
render();
