export const colors=['#ff6666','#66cc66','#6699ff','#fb60fc','#ffa500','#8a2be2'];
export const code=r=>`${r.PLANT}_${r.ROW}_${String(r.BAY).padStart(2,'0')}_${r.LEVEL}_${r.SIDE}`;
export const levelColor=(l,palette=colors)=>palette[Number(l)-1]||'#a0a0a0';
const rgb=hex=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));
const hslHex=(h,s,l)=>{s/=100;l/=100;const a=s*Math.min(l,1-l),f=n=>{const k=(n+h/30)%12;return l-a*Math.max(-1,Math.min(k-3,9-k,1));};return '#'+[f(0),f(8),f(4)].map(v=>Math.round(255*v).toString(16).padStart(2,'0')).join('');};
export function extendLevelColors(existing,count,random=Math.random){const out=[...existing];while(out.length<count){const offset=random()*360,used=out.map(rgb);let best='#808080',bestScore=-1;for(let i=0;i<96;i++){const candidate=hslHex((offset+i*137.508)%360,65+(i%3)*10,42+(i%4)*7),value=rgb(candidate),score=used.length?Math.min(...used.map(c=>c.reduce((sum,v,j)=>sum+(v-value[j])**2,0))):Infinity;if(!out.includes(candidate)&&score>bestScore){best=candidate;bestScore=score;}}out.push(best);}return out;}
export const bayLevels=(row,bay)=>row.bayLevels?.[bay]??row.levels;
export function rotatePoint(gx,gy,size,rotation){const n=size-1;return rotation===0?[gx,gy]:rotation===1?[n-gy,gx]:rotation===2?[n-gx,n-gy]:[gy,n-gx];}
export function unrotatePoint(gx,gy,size,rotation){const n=size-1;return rotation===0?[gx,gy]:rotation===1?[gy,n-gx]:rotation===2?[n-gx,n-gy]:[n-gy,gx];}
export function isoPoint(gx,gy,size,rotation){const [rx,ry]=rotatePoint(gx,gy,size,rotation);return {x:size*42+70+(rx-ry)*42,y:55+(rx+ry)*22};}
export function gridAtIsoPoint(x,y,size,rotation){const a=(x-(size*42+70))/42,b=(y-55)/22;const [gx,gy]=unrotatePoint(Math.round((a+b)/2),Math.round((b-a)/2),size,rotation);return {gx,gy};}
export function topPoint(gx,gy,size,rotation){const [rx,ry]=rotatePoint(gx,gy,size,rotation);return {x:45+rx*42,y:45+ry*42};}
export function gridAtTopPoint(x,y,size,rotation){const [gx,gy]=unrotatePoint(Math.round((x-45)/42),Math.round((y-45)/42),size,rotation);return {gx,gy};}
export function hasAdjacentPath(unit,paths){return paths.some(p=>Math.abs(p.gx-unit.gx)+Math.abs(p.gy-unit.gy)===1);}
export function placementIdentity(units,grid,forcedRow){const neighbor=units.find(u=>Math.abs(u.gx-grid.gx)+Math.abs(u.gy-grid.gy)===1),row=forcedRow??neighbor?.row??nextAvailableRow(units),bay=Math.max(0,...units.filter(u=>u.row===row).map(u=>u.bay))+1;return {row,bay};}
export function assignSelectionRow(units,ids,row){const selected=new Set(ids),items=units.filter(u=>selected.has(u.id)).sort((a,b)=>a.gy-b.gy||a.gx-b.gx),start=Math.max(0,...units.filter(u=>!selected.has(u.id)&&u.row===row).map(u=>u.bay))+1;items.forEach((u,i)=>{u.row=row;u.bay=start+i;});return items;}
export function gridLine(from,to){const points=[],dx=Math.abs(to.gx-from.gx),dy=Math.abs(to.gy-from.gy),sx=from.gx<to.gx?1:-1,sy=from.gy<to.gy?1:-1;let x=from.gx,y=from.gy,err=dx-dy;for(;;){points.push({gx:x,gy:y});if(x===to.gx&&y===to.gy)break;const e=2*err;if(e>-dy){err-=dy;x+=sx;}if(e<dx){err+=dx;y+=sy;}}return points;}
export function contentsAtGrids(units,paths,points){const keys=new Set(points.map(p=>`${p.gx},${p.gy}`));return {unitIds:units.filter(u=>keys.has(`${u.gx},${u.gy}`)).map(u=>u.id),pathKeys:paths.filter(p=>keys.has(`${p.gx},${p.gy}`)).map(p=>`${p.gx},${p.gy}`)};}
export function rowNameAt(index){const length=Math.floor(index/26)+1;return 'A'.repeat(length-1)+String.fromCharCode(65+index%26);}
function nextAvailableRow(units){const used=new Set(units.map(u=>u.row));for(let i=0;;i++){const name=rowNameAt(i);if(!used.has(name))return name;}}
export function locations(s){if(s.imported)return s.imported;const out=[];if(Array.isArray(s.units)){for(const u of [...s.units].sort((a,b)=>a.row.localeCompare(b.row)||a.bay-b.bay))for(let l=1;l<=u.levels;l++){const n=u.capacities?.[l]??2;for(const side of n===2?['L','R']:n===1?['S']:[])out.push({PLANT:s.plant,ROW:u.row,BAY:String(u.bay).padStart(2,'0'),LEVEL:String(l),SIDE:side});}return out;}for(const row of s.rows)for(let b=1;b<=row.bays;b++)for(let l=1;l<=bayLevels(row,b);l++){const n=row.cells[`${b}:${l}`]??2;for(const side of n===2?['L','R']:n===1?['S']:[])out.push({PLANT:s.plant,ROW:row.name,BAY:String(b).padStart(2,'0'),LEVEL:String(l),SIDE:side});}return out;}
export function labelGroups(records){const groups=new Map();for(const r of records){const key=`${r.PLANT}_${r.ROW}_${r.BAY}_${r.SIDE}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}return [...groups.entries()].map(([key,items])=>({key,items:items.sort((a,b)=>Number(a.LEVEL)-Number(b.LEVEL))}));}
export function normalize(table){if(!table.length)throw Error('ไฟล์ว่าง');const headers=table[0].map(v=>String(v??'').trim().toUpperCase()),required=['PLANT','ROW','BAY','LEVEL','SIDE'];if(!required.every(h=>headers.includes(h)))throw Error('ต้องมีคอลัมน์ PLANT, ROW, BAY, LEVEL, SIDE');const seen=new Set();return table.slice(1).filter(r=>r.some(v=>String(v??'').trim())).map((r,i)=>{const obj=Object.fromEntries(required.map(h=>[h,String(r[headers.indexOf(h)]??'').trim().toUpperCase()]));if(!/^[A-Z0-9-]+$/.test(obj.PLANT)||!/^[A-Z0-9-]+$/.test(obj.ROW)||!/^\d+$/.test(obj.BAY)||Number(obj.BAY)<1||!/^\d+$/.test(obj.LEVEL)||Number(obj.LEVEL)<1||!['L','R','S'].includes(obj.SIDE))throw Error(`ข้อมูลแถว ${i+2} ไม่ถูกต้อง`);obj.BAY=String(Number(obj.BAY)).padStart(2,'0');obj.LEVEL=String(Number(obj.LEVEL));const key=code(obj);if(seen.has(key))throw Error(`Location ซ้ำ: ${key}`);seen.add(key);return obj;});}
const rack=(id,name,x,y,orientation='horizontal')=>({id,name,bays:4,levels:3,x,y,orientation,bayLevels:{},cells:{}});
export function defaultLabel(){return {template:null,width:900,height:300,levelColors:[...colors],components:[{id:1,type:'color',x:0,y:0,w:900,h:300,fg:'#66cc66',bg:'transparent',auto:true,size:40},{id:2,type:'rect',x:12,y:12,w:876,h:276,fg:'#ffffff',bg:'#ffffff',size:40},{id:3,type:'qr',x:26,y:26,w:248,h:248,fg:'#000000',bg:'#ffffff',size:40},...['PLANT','ROW','BAY','LEVEL','SIDE'].map((type,i)=>({id:i+4,type,x:300+i*108,y:150,w:103,h:105,fg:'#14283f',bg:'transparent',size:38})),{id:9,type:'arrow',x:590,y:20,w:170,h:115,fg:'#14283f',bg:'transparent',size:80,auto:true,direction:'↑'}]};}
export function defaultLayout(){return {gridSize:14,units:[{id:101,gx:4,gy:4,row:'A',bay:1,levels:3,capacities:{}},{id:102,gx:5,gy:4,row:'A',bay:2,levels:3,capacities:{}},{id:103,gx:6,gy:4,row:'A',bay:3,levels:3,capacities:{}}],paths:[{gx:4,gy:5},{gx:5,gy:5},{gx:6,gy:5}],rows:[rack(1,'A',120,150)],aisles:[]};}
export function defaultState(){return {version:5,plant:'ANV1',imported:null,ignoreInvalidRacks:false,...defaultLayout(),...defaultLabel()};}
export function csv(records){return '\ufeffPLANT,ROW,BAY,LEVEL,SIDE,Location_Code\r\n'+records.map(r=>[r.PLANT,r.ROW,r.BAY,r.LEVEL,r.SIDE,code(r)].join(',')).join('\r\n');}
export const exampleRows=[{PLANT:'ANV1',ROW:'A',BAY:'01',LEVEL:'1',SIDE:'L'},{PLANT:'ANV1',ROW:'A',BAY:'01',LEVEL:'1',SIDE:'R'},{PLANT:'ANV1',ROW:'A',BAY:'01',LEVEL:'2',SIDE:'L'},{PLANT:'ANV1',ROW:'A',BAY:'01',LEVEL:'2',SIDE:'R'}];
