export const colors=['#ff6666','#66cc66','#6699ff','#fb60fc','#ffa500','#8a2be2'];
export const code=r=>`${r.PLANT}_${r.ROW}_${String(r.BAY).padStart(2,'0')}_${r.LEVEL}_${r.SIDE}`;
export const levelColor=l=>colors[Number(l)-1]||'#a0a0a0';
export const bayLevels=(row,bay)=>row.bayLevels?.[bay]??row.levels;
export function locations(s){if(s.imported)return s.imported;const out=[];if(Array.isArray(s.units)){for(const u of [...s.units].sort((a,b)=>a.row.localeCompare(b.row)||a.bay-b.bay))for(let l=1;l<=u.levels;l++){const n=u.capacities?.[l]??2;for(const side of n===2?['L','R']:n===1?['S']:[])out.push({PLANT:s.plant,ROW:u.row,BAY:String(u.bay).padStart(2,'0'),LEVEL:String(l),SIDE:side});}return out;}for(const row of s.rows)for(let b=1;b<=row.bays;b++)for(let l=1;l<=bayLevels(row,b);l++){const n=row.cells[`${b}:${l}`]??2;for(const side of n===2?['L','R']:n===1?['S']:[])out.push({PLANT:s.plant,ROW:row.name,BAY:String(b).padStart(2,'0'),LEVEL:String(l),SIDE:side});}return out;}
export function labelGroups(records){const groups=new Map();for(const r of records){const key=`${r.PLANT}_${r.ROW}_${r.BAY}_${r.SIDE}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}return [...groups.entries()].map(([key,items])=>({key,items:items.sort((a,b)=>Number(a.LEVEL)-Number(b.LEVEL))}));}
export function normalize(table){if(!table.length)throw Error('ไฟล์ว่าง');const headers=table[0].map(v=>String(v??'').trim().toUpperCase()),required=['PLANT','ROW','BAY','LEVEL','SIDE'];if(!required.every(h=>headers.includes(h)))throw Error('ต้องมีคอลัมน์ PLANT, ROW, BAY, LEVEL, SIDE');const seen=new Set();return table.slice(1).filter(r=>r.some(v=>String(v??'').trim())).map((r,i)=>{const obj=Object.fromEntries(required.map(h=>[h,String(r[headers.indexOf(h)]??'').trim().toUpperCase()]));if(!/^[A-Z0-9-]+$/.test(obj.PLANT)||!/^[A-Z0-9-]+$/.test(obj.ROW)||!/^\d+$/.test(obj.BAY)||Number(obj.BAY)<1||!/^\d+$/.test(obj.LEVEL)||Number(obj.LEVEL)<1||!['L','R','S'].includes(obj.SIDE))throw Error(`ข้อมูลแถว ${i+2} ไม่ถูกต้อง`);obj.BAY=String(Number(obj.BAY)).padStart(2,'0');obj.LEVEL=String(Number(obj.LEVEL));const key=code(obj);if(seen.has(key))throw Error(`Location ซ้ำ: ${key}`);seen.add(key);return obj;});}
const rack=(id,name,x,y,orientation='horizontal')=>({id,name,bays:4,levels:3,x,y,orientation,bayLevels:{},cells:{}});
export function defaultLabel(){return {template:null,width:900,height:300,components:[{id:1,type:'color',x:0,y:0,w:900,h:300,fg:'#66cc66',bg:'transparent',auto:true,size:40},{id:2,type:'rect',x:12,y:12,w:876,h:276,fg:'#ffffff',bg:'#ffffff',size:40},{id:3,type:'qr',x:26,y:26,w:248,h:248,fg:'#000000',bg:'#ffffff',size:40},...['PLANT','ROW','BAY','LEVEL','SIDE'].map((type,i)=>({id:i+4,type,x:300+i*108,y:150,w:103,h:105,fg:'#14283f',bg:'transparent',size:38})),{id:9,type:'arrow',x:590,y:20,w:170,h:115,fg:'#14283f',bg:'transparent',size:80,auto:true,direction:'↑'}]};}
export function defaultLayout(){return {units:[{id:101,gx:4,gy:4,row:'A',bay:1,levels:3,capacities:{}},{id:102,gx:5,gy:4,row:'A',bay:2,levels:3,capacities:{}},{id:103,gx:6,gy:4,row:'A',bay:3,levels:3,capacities:{}}],paths:[{gx:4,gy:5},{gx:5,gy:5},{gx:6,gy:5}],rows:[rack(1,'A',120,150)],aisles:[]};}
export function defaultState(){return {version:3,plant:'ANV1',imported:null,...defaultLayout(),...defaultLabel()};}
export function csv(records){return '\ufeffPLANT,ROW,BAY,LEVEL,SIDE,Location_Code\r\n'+records.map(r=>[r.PLANT,r.ROW,r.BAY,r.LEVEL,r.SIDE,code(r)].join(',')).join('\r\n');}
export const exampleRows=[{PLANT:'ANV1',ROW:'A',BAY:'01',LEVEL:'1',SIDE:'L'},{PLANT:'ANV1',ROW:'A',BAY:'01',LEVEL:'1',SIDE:'R'},{PLANT:'ANV1',ROW:'A',BAY:'01',LEVEL:'2',SIDE:'L'},{PLANT:'ANV1',ROW:'A',BAY:'01',LEVEL:'2',SIDE:'R'}];
