import QRCode from 'qrcode';
import JsBarcode from 'jsbarcode';
import {levelColor,code} from './model.js';
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cache=new Map();
export async function componentContent(c,r){if(c.type==='qr'){const key=code(r);if(!cache.has(key))cache.set(key,QRCode.toString(key,{type:'svg',margin:4,errorCorrectionLevel:'M'}));return cache.get(key);}if(c.type==='barcode'){const el=document.createElementNS('http://www.w3.org/2000/svg','svg');JsBarcode(el,code(r),{format:'CODE128',displayValue:false,margin:12,height:70});return el.outerHTML;}if(['rect','color','image'].includes(c.type))return '';if(c.type==='arrow')return `<span class="arrow">${c.auto?(r.LEVEL==='1'?'↓':'↑'):esc(c.direction)}</span>`;return `<small>${esc(c.type)}</small><strong>${esc(r[c.type]??code(r))}</strong>`;}
function fitSize(text,max,w,h){return Math.max(7,Math.min(max,w/Math.max(1,String(text).length*.62),h*.48));}
export async function labelSVG(s,r){const pieces=[];for(const c of s.components){let inner=await componentContent(c,r),value=r[c.type]??code(r),fill=c.type==='color'?(c.auto?levelColor(r.LEVEL,s.levelColors):c.fg):c.type==='rect'?c.fg:c.bg;pieces.push(`<g transform="translate(${c.x} ${c.y})">`);if(c.type==='image')pieces.push(`<image href="${esc(c.src)}" width="${c.w}" height="${c.h}" preserveAspectRatio="xMidYMid meet"/>`);else{pieces.push(`<rect width="${c.w}" height="${c.h}" fill="${fill==='transparent'?'none':esc(fill)}"/>`);if(c.type==='qr'||c.type==='barcode'){inner=inner.replace(/<svg[^>]*>/,m=>m.replace(/width="[^"]*"|height="[^"]*"/g,'').replace('<svg',`<svg width="${c.w}" height="${c.h}"`));pieces.push(inner);}else if(c.type==='arrow')pieces.push(`<text x="${c.w/2}" y="${c.h*.78}" text-anchor="middle" font-family="Arial,sans-serif" font-size="${Math.min(c.size,c.h*.82)}" fill="${esc(c.fg)}">${c.auto?(r.LEVEL==='1'?'↓':'↑'):esc(c.direction)}</text>`);else if(!['rect','color'].includes(c.type)){const header=Math.max(7,Math.min(14,c.h*.18,c.w/Math.max(1,c.type.length*.62))),size=fitSize(value,c.size,c.w-6,c.h-header-8);pieces.push(`<text x="${c.w/2}" y="${header+3}" text-anchor="middle" font-family="Arial,sans-serif" font-size="${header}" fill="${esc(c.fg)}">${esc(c.type)}</text><text x="${c.w/2}" y="${Math.min(c.h-5,header+8+size)}" text-anchor="middle" font-family="Arial,sans-serif" font-weight="700" font-size="${size}" fill="${esc(c.fg)}">${esc(value)}</text>`);}}pieces.push('</g>');}return `<svg xmlns="http://www.w3.org/2000/svg" width="${s.printWidth}${s.printUnit}" height="${s.printHeight}${s.printUnit}" viewBox="0 0 ${s.width} ${s.height}"><rect width="100%" height="100%" fill="white"/>${s.template?`<image href="${s.template}" width="100%" height="100%" preserveAspectRatio="none"/>`:''}${pieces.join('')}</svg>`;}
export async function pngFromSVG(svg,width,height,scale=1){const url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=width*scale;canvas.height=height*scale;canvas.getContext('2d').drawImage(img,0,0,canvas.width,canvas.height);return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('สร้าง PNG ไม่สำเร็จ')),'image/png'));}finally{URL.revokeObjectURL(url);}}
export async function png(s,r){return pngFromSVG(await labelSVG(s,r),s.width,s.height);}
export async function combinedSVG(s,items,direction='vertical'){const vertical=direction==='vertical',width=vertical?s.width:s.width*items.length,height=vertical?s.height*items.length:s.height,physicalWidth=vertical?s.printWidth:s.printWidth*items.length,physicalHeight=vertical?s.printHeight*items.length:s.printHeight,labels=await Promise.all(items.map(r=>labelSVG(s,r))),body=labels.map((svg,i)=>`<g transform="translate(${vertical?0:i*s.width} ${vertical?i*s.height:0})">${svg.replace(/^<svg[^>]*>|<\/svg>$/g,'')}</g>`).join('');return {svg:`<svg xmlns="http://www.w3.org/2000/svg" width="${physicalWidth}${s.printUnit}" height="${physicalHeight}${s.printUnit}" viewBox="0 0 ${width} ${height}">${body}</svg>`,width,height};}
