export const colors=['#ff6666','#66cc66','#6699ff','#fb60fc','#ffa500','#8a2be2'];
export const MAX_GRID_SIZE=125;
export const code=r=>`${r.PLANT}_${r.ROW}_${String(r.BAY).padStart(2,'0')}_${r.LEVEL}_${r.SIDE}`;
export const levelColor=(l,palette=colors)=>palette[Number(l)-1]||'#a0a0a0';
const rgb=hex=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16));
const hslHex=(h,s,l)=>{s/=100;l/=100;const a=s*Math.min(l,1-l),f=n=>{const k=(n+h/30)%12;return l-a*Math.max(-1,Math.min(k-3,9-k,1));};return '#'+[f(0),f(8),f(4)].map(v=>Math.round(255*v).toString(16).padStart(2,'0')).join('');};
export function extendLevelColors(existing,count,random=Math.random){const out=[...existing];while(out.length<count){const offset=random()*360,used=out.map(rgb);let best='#808080',bestScore=-1;for(let i=0;i<96;i++){const candidate=hslHex((offset+i*137.508)%360,65+(i%3)*10,42+(i%4)*7),value=rgb(candidate),score=used.length?Math.min(...used.map(c=>c.reduce((sum,v,j)=>sum+(v-value[j])**2,0))):Infinity;if(!out.includes(candidate)&&score>bestScore){best=candidate;bestScore=score;}}out.push(best);}return out;}
export const bayLevels=(row,bay)=>row.bayLevels?.[bay]??row.levels;
export function rotatePoint(gx,gy,size,rotation){const n=size-1;return rotation===0?[gx,gy]:rotation===1?[n-gy,gx]:rotation===2?[n-gx,n-gy]:[gy,n-gx];}
export function unrotatePoint(gx,gy,size,rotation){const n=size-1;return rotation===0?[gx,gy]:rotation===1?[gy,n-gx]:rotation===2?[n-gx,n-gy]:[n-gy,gx];}
export function isoPoint(gx,gy,size,rotation){const [rx,ry]=rotatePoint(gx,gy,size,rotation);return {x:size*42+70+(rx-ry)*42,y:55+(rx+ry)*22};}
export function gridAtIsoPoint(x,y,size,rotation){const a=(x-(size*42+70))/42,b=(y-55)/22;const [gx,gy]=unrotatePoint(Math.round((a+b)/2),Math.round((b-a)/2),size,rotation);return {gx,gy};}
export function topPoint(gx,gy,size,rotation){const [rx,ry]=rotatePoint(gx,gy,size,rotation);return {x:45+rx*42,y:45+ry*42};}
export function gridAtTopPoint(x,y,size,rotation){const [gx,gy]=unrotatePoint(Math.round((x-45)/42),Math.round((y-45)/42),size,rotation);return {gx,gy};}
export function finiteGridCell(cell,size){const gx=Math.floor(Number(cell?.gx)),gy=Math.floor(Number(cell?.gy));return Number.isFinite(gx)&&Number.isFinite(gy)&&gx>=0&&gy>=0&&gx<size&&gy<size?{gx,gy}:null;}
export function zoomTargetCorrection(before,after){return {x:Number(before.x)-Number(after.x),z:Number(before.z)-Number(after.z)};}
export function rackZoomBounds(gridSize=14){const size=Math.max(1,Number(gridSize)||14);return {min:Math.min(.5,7/size),max:Math.max(2,size/7)};}
export function clampRackZoom(value,gridSize=14){const bounds=rackZoomBounds(gridSize);return Math.max(bounds.min,Math.min(bounds.max,Number(value)||1));}
export function rackColumns(unit){let enabled=false;for(let level=1;level<=Math.max(1,Number(unit?.levels)||1);level++){const capacity=Number(unit?.capacities?.[level]??2);if(capacity>0)enabled=true;if(capacity===2)return 2;}return enabled?1:1;}
export function rackVisualBins(capacity){const columns=Number(capacity)===2?[-.46,.46]:Number(capacity)===1?[0]:[];return columns.flatMap(x=>[0,1].map(row=>({x,row})));}
export function rackLabelWidth(){return 1.68;}
export function rackDirection(unit){const value=Number(unit?.direction);return Number.isInteger(value)?((value%4)+4)%4:unit?.axis==='y'?1:0;}
export function rackAxis(unit){return rackDirection(unit)%2?'y':'x';}
export function unitFootprint(unit){const count=rackColumns(unit),axis=rackAxis(unit);return Array.from({length:count},(_,i)=>({gx:Number(unit.gx)+(axis==='x'?i:0),gy:Number(unit.gy)+(axis==='y'?i:0)}));}
export function frontPathCells(unit){const direction=rackDirection(unit),vectors=[[0,1],[1,0],[0,-1],[-1,0]],vector=vectors[direction];return unitFootprint(unit).map(cell=>({gx:cell.gx+vector[0],gy:cell.gy+vector[1]}));}
export function rotatedRack(unit,quarterTurns=1){const direction=(rackDirection(unit)+Number(quarterTurns||0)+4*1000)%4;return {...unit,direction,axis:direction%2?'y':'x'};}
export function canPlaceUnit(candidate,units,paths,gridSize){const cells=unitFootprint(candidate),blocked=new Set(paths.map(p=>`${p.gx},${p.gy}`));for(const unit of units)if(unit.id!==candidate.id)for(const cell of unitFootprint(unit))blocked.add(`${cell.gx},${cell.gy}`);return cells.every(cell=>cell.gx>=0&&cell.gy>=0&&cell.gx<gridSize&&cell.gy<gridSize&&!blocked.has(`${cell.gx},${cell.gy}`));}
export function migrateLegacyFootprints(units,paths,gridSize){for(const unit of units){if(!['x','y'].includes(unit.axis)){const row=units.filter(other=>other.id!==unit.id&&other.row===unit.row),rangeX=row.length?Math.max(...row.map(other=>other.gx),unit.gx)-Math.min(...row.map(other=>other.gx),unit.gx):1,rangeY=row.length?Math.max(...row.map(other=>other.gy),unit.gy)-Math.min(...row.map(other=>other.gy),unit.gy):0;unit.axis=rangeY>rangeX?'y':'x';}unit.direction=rackDirection(unit);unit.axis=rackAxis(unit);}const accepted=[];for(const unit of units){if(!canPlaceUnit(unit,accepted,paths,gridSize)){const origin={gx:unit.gx,gy:unit.gy};let placed=false;for(let step=1;step<gridSize&&!placed;step++){unit.gx=origin.gx+(rackAxis(unit)==='x'?step:0);unit.gy=origin.gy+(rackAxis(unit)==='y'?step:0);placed=canPlaceUnit(unit,accepted,paths,gridSize);}if(!placed)for(let gy=0;gy<gridSize&&!placed;gy++)for(let gx=0;gx<gridSize&&!placed;gx++){unit.gx=gx;unit.gy=gy;placed=canPlaceUnit(unit,accepted,paths,gridSize);}if(!placed){unit.gx=origin.gx;unit.gy=origin.gy;}}accepted.push(unit);}return units;}
export function hasAdjacentPath(unit,paths){const available=new Set(paths.map(path=>`${path.gx},${path.gy}`));return frontPathCells(unit).every(cell=>available.has(`${cell.gx},${cell.gy}`));}
export function rackVisualState(unit,paths,selected=false,erasing=false){if(erasing)return 'erase';if(selected)return 'active';if(!hasAdjacentPath(unit,paths))return 'invalid';return 'normal';}
export function nextBayForRow(units,row){return Math.max(0,...units.filter(unit=>unit.row===row).map(unit=>Number(unit.bay)||0))+1;}
export function placementIdentity(units,grid,forcedRow,axis='x',capacity=2){const direction=axis==='y'?1:0,candidate=unitFootprint({...grid,axis,direction,levels:1,capacities:{1:capacity}}),neighbor=units.find(unit=>unitFootprint(unit).some(cell=>candidate.some(next=>Math.abs(cell.gx-next.gx)+Math.abs(cell.gy-next.gy)===1))),row=forcedRow??neighbor?.row??nextAvailableRow(units);return {row,bay:nextBayForRow(units,row)};}
export function assignSelectionRow(units,ids,row){const selected=new Set(ids),items=units.filter(u=>selected.has(u.id)).sort((a,b)=>a.gy-b.gy||a.gx-b.gx),start=Math.max(0,...units.filter(u=>!selected.has(u.id)&&u.row===row).map(u=>u.bay))+1;items.forEach((u,i)=>{u.row=row;u.bay=start+i;});return items;}
export function rackIdsInRow(units,row){const wanted=String(row??'').trim().toUpperCase();return units.filter(unit=>String(unit.row??'').trim().toUpperCase()===wanted).map(unit=>unit.id);}
export function connectedRackIds(units,seedIds,axis='x'){const selected=new Set(seedIds),pending=units.filter(unit=>selected.has(unit.id)),alongX=axis==='x',touches=(left,right)=>unitFootprint(left).some(a=>unitFootprint(right).some(b=>alongX?a.gy===b.gy&&Math.abs(a.gx-b.gx)===1:a.gx===b.gx&&Math.abs(a.gy-b.gy)===1));while(pending.length){const current=pending.shift();for(const candidate of units)if(!selected.has(candidate.id)&&touches(current,candidate)){selected.add(candidate.id);pending.push(candidate);}}return units.filter(unit=>selected.has(unit.id)).map(unit=>unit.id);}
export function gridLine(from,to){const points=[],dx=Math.abs(to.gx-from.gx),dy=Math.abs(to.gy-from.gy),sx=from.gx<to.gx?1:-1,sy=from.gy<to.gy?1:-1;let x=from.gx,y=from.gy,err=dx-dy;for(;;){points.push({gx:x,gy:y});if(x===to.gx&&y===to.gy)break;const e=2*err;if(e>-dy){err-=dy;x+=sx;}if(e<dx){err+=dx;y+=sy;}}return points;}
export function gridRectangle(from,to){const points=[];for(let gy=Math.min(from.gy,to.gy);gy<=Math.max(from.gy,to.gy);gy++)for(let gx=Math.min(from.gx,to.gx);gx<=Math.max(from.gx,to.gx);gx++)points.push({gx,gy});return points;}
export function contentsAtGrids(units,paths,points){const keys=new Set(points.map(p=>`${p.gx},${p.gy}`));return {unitIds:units.filter(u=>unitFootprint(u).some(cell=>keys.has(`${cell.gx},${cell.gy}`))).map(u=>u.id),pathKeys:paths.filter(p=>keys.has(`${p.gx},${p.gy}`)).map(p=>`${p.gx},${p.gy}`)};}
export function selectionAnchor(units,paths,unitIds,pathKeys){const ids=new Set(unitIds),keys=new Set(pathKeys),cells=[...units.filter(unit=>ids.has(unit.id)).flatMap(unitFootprint),...paths.filter(path=>keys.has(`${path.gx},${path.gy}`))];if(!cells.length)return null;return {gx:Math.min(...cells.map(cell=>cell.gx)),gy:Math.min(...cells.map(cell=>cell.gy))};}
export function planSelectionMove(units,paths,unitIds,pathKeys,target,gridSize){const anchor=selectionAnchor(units,paths,unitIds,pathKeys);if(!anchor)return {valid:false,delta:{gx:0,gy:0},units:[],paths:[],reason:'empty'};const delta={gx:Number(target.gx)-anchor.gx,gy:Number(target.gy)-anchor.gy},ids=new Set(unitIds),keys=new Set(pathKeys),movedUnits=units.filter(unit=>ids.has(unit.id)).map(unit=>({...unit,gx:unit.gx+delta.gx,gy:unit.gy+delta.gy})),movedPaths=paths.filter(path=>keys.has(`${path.gx},${path.gy}`)).map(path=>({gx:path.gx+delta.gx,gy:path.gy+delta.gy})),occupied=new Set();for(const unit of units)if(!ids.has(unit.id))for(const cell of unitFootprint(unit))occupied.add(`${cell.gx},${cell.gy}`);for(const path of paths)if(!keys.has(`${path.gx},${path.gy}`))occupied.add(`${path.gx},${path.gy}`);const accept=cell=>cell.gx>=0&&cell.gy>=0&&cell.gx<gridSize&&cell.gy<gridSize&&!occupied.has(`${cell.gx},${cell.gy}`);for(const unit of movedUnits)for(const cell of unitFootprint(unit)){if(!accept(cell))return {valid:false,delta,units:movedUnits,paths:movedPaths,reason:'blocked'};occupied.add(`${cell.gx},${cell.gy}`);}for(const path of movedPaths){if(!accept(path))return {valid:false,delta,units:movedUnits,paths:movedPaths,reason:'blocked'};occupied.add(`${path.gx},${path.gy}`);}return {valid:true,delta,units:movedUnits,paths:movedPaths,reason:''};}
export function planSelectionRotation(units,paths,unitIds,pathKeys,quarterTurns=1,gridSize=14){const ids=new Set(unitIds),keys=new Set(pathKeys),selectedUnits=units.filter(unit=>ids.has(unit.id)),selectedPaths=paths.filter(path=>keys.has(`${path.gx},${path.gy}`)),cells=[...selectedUnits.flatMap(unitFootprint),...selectedPaths];if(!cells.length)return {valid:false,units:[],paths:[],reason:'empty'};let bounds={minX:Math.min(...cells.map(cell=>cell.gx)),maxX:Math.max(...cells.map(cell=>cell.gx)),minY:Math.min(...cells.map(cell=>cell.gy)),maxY:Math.max(...cells.map(cell=>cell.gy))};const turns=((Number(quarterTurns)||0)%4+4)%4,rotate=cell=>{let next={...cell},box={...bounds};for(let turn=0;turn<turns;turn++){next={gx:box.minX+box.maxY-next.gy,gy:box.minY+next.gx-box.minX};box={minX:box.minX,maxX:box.minX+box.maxY-box.minY,minY:box.minY,maxY:box.minY+box.maxX-box.minX};}return next;},movedUnits=selectedUnits.map(unit=>{const footprint=unitFootprint(unit).map(rotate),candidate=rotatedRack(unit,turns);return {...candidate,gx:Math.min(...footprint.map(cell=>cell.gx)),gy:Math.min(...footprint.map(cell=>cell.gy))};}),movedPaths=selectedPaths.map(rotate),occupied=new Set();for(const unit of units)if(!ids.has(unit.id))for(const cell of unitFootprint(unit))occupied.add(`${cell.gx},${cell.gy}`);for(const path of paths)if(!keys.has(`${path.gx},${path.gy}`))occupied.add(`${path.gx},${path.gy}`);const claim=cell=>{const key=`${cell.gx},${cell.gy}`;if(cell.gx<0||cell.gy<0||cell.gx>=gridSize||cell.gy>=gridSize||occupied.has(key))return false;occupied.add(key);return true;};for(const unit of movedUnits)for(const cell of unitFootprint(unit))if(!claim(cell))return {valid:false,units:movedUnits,paths:movedPaths,reason:'blocked'};for(const path of movedPaths)if(!claim(path))return {valid:false,units:movedUnits,paths:movedPaths,reason:'blocked'};return {valid:true,units:movedUnits,paths:movedPaths,reason:''};}
export function planSelectionTransform(units,paths,unitIds,pathKeys,target,quarterTurns=0,gridSize=14){const ids=new Set(unitIds),keys=new Set(pathKeys),rotation=planSelectionRotation(units,paths,unitIds,pathKeys,quarterTurns,gridSize),rotatedPathKeys=rotation.paths.map(path=>`${path.gx},${path.gy}`),stagedUnits=[...units.filter(unit=>!ids.has(unit.id)),...rotation.units],stagedPaths=[...paths.filter(path=>!keys.has(`${path.gx},${path.gy}`)),...rotation.paths],move=planSelectionMove(stagedUnits,stagedPaths,unitIds,rotatedPathKeys,target,gridSize);return {...move,turns:((Number(quarterTurns)||0)%4+4)%4};}
export function directionFacingPath(unit,paths,preferredDirection=0){const preferred=rackDirection({direction:preferredDirection}),single=rackColumns(unit)===1,base=rackAxis(unit)==='y'?1:0,primary=single?preferred:(preferred%2===base?preferred:base),directions=single?[primary,(primary+1)%4,(primary+2)%4,(primary+3)%4]:[primary,(primary+2)%4];for(const direction of directions)if(hasAdjacentPath({...unit,direction,axis:direction%2?'y':'x'},paths))return direction;return primary;}
export function adjustSelectedRackLevels(units,unitIds,delta,minLevel=1,maxLevel=12){const ids=new Set(unitIds),change=Math.trunc(Number(delta)||0);return units.map(unit=>{if(!ids.has(unit.id)||!change)return {...unit,capacities:{...unit.capacities}};const capacities={...unit.capacities},current=Math.max(minLevel,Math.min(maxLevel,Number(unit.levels)||minLevel)),target=Math.max(minLevel,Math.min(maxLevel,current+change));if(target>current)for(let level=current+1;level<=target;level++)capacities[level]=Number(capacities[level-1]??2);else for(const key of Object.keys(capacities))if(Number(key)>target)delete capacities[key];return {...unit,levels:target,capacities};});}
export function setSelectedRackLevels(units,unitIds,targetLevel,minLevel=1,maxLevel=12){const ids=new Set(unitIds),target=Math.max(minLevel,Math.min(maxLevel,Math.trunc(Number(targetLevel)||minLevel)));return units.map(unit=>{if(!ids.has(unit.id))return {...unit,capacities:{...unit.capacities}};const capacities={...unit.capacities},current=Math.max(minLevel,Math.min(maxLevel,Number(unit.levels)||minLevel));if(target>current)for(let level=current+1;level<=target;level++)capacities[level]=Number(capacities[level-1]??2);else for(const key of Object.keys(capacities))if(Number(key)>target)delete capacities[key];return {...unit,levels:target,capacities};});}
export function applySelectedRackSettings(units,unitIds,levels,row){const next=setSelectedRackLevels(units,unitIds,levels);assignSelectionRow(next,unitIds,row);return next;}
const sceneUnitSignature=unit=>JSON.stringify([unit.gx,unit.gy,rackDirection(unit),unit.row,unit.bay,Number(unit.levels)||1,Array.from({length:Math.max(1,Number(unit.levels)||1)},(_,i)=>Number(unit.capacities?.[i+1]??2))]);
export function rackSceneSnapshot(units,paths){return {units:units.map(unit=>[unit.id,sceneUnitSignature(unit)]),paths:paths.map(path=>`${path.gx},${path.gy}`).sort()};}
export function rackSceneChanges(previous,units,paths){const next=rackSceneSnapshot(units,paths),beforeUnits=new Map(previous?.units??[]),afterUnits=new Map(next.units),beforePaths=new Set(previous?.paths??[]),afterPaths=new Set(next.paths);return {addUnits:next.units.filter(([id])=>!beforeUnits.has(id)).map(([id])=>id),updateUnits:next.units.filter(([id,signature])=>beforeUnits.has(id)&&beforeUnits.get(id)!==signature).map(([id])=>id),removeUnits:[...beforeUnits.keys()].filter(id=>!afterUnits.has(id)),addPaths:next.paths.filter(key=>!beforePaths.has(key)),removePaths:[...beforePaths].filter(key=>!afterPaths.has(key)),next};}
export function toggleItemSelection(selected,id,additive=false){if(!additive)return [id];return selected.includes(id)?selected.filter(value=>value!==id):[...selected,id];}
export function removeSelectedItems(items,selected){const ids=new Set(selected);return items.filter(item=>!ids.has(item.id));}
export function alignmentGuides(moving,components,tolerance=2){const axes=item=>{const angle=componentTransform(item).rotation*Math.PI/180,cos=Math.abs(Math.cos(angle)),sin=Math.abs(Math.sin(angle)),width=item.w*cos+item.h*sin,height=item.w*sin+item.h*cos,cx=item.x+item.w/2,cy=item.y+item.h/2;return {vertical:[cx-width/2,cx,cx+width/2],horizontal:[cy-height/2,cy,cy+height/2]};},movingAxes=axes(moving),result={vertical:[],horizontal:[]};for(const component of components){if(component.id===moving.id)continue;const other=axes(component);for(const key of ['vertical','horizontal'])for(const a of movingAxes[key])if(other[key].some(b=>Math.abs(a-b)<=tolerance))result[key].push(a);}for(const key of ['vertical','horizontal'])result[key]=[...new Set(result[key].map(value=>Math.round(value*100)/100))].sort((a,b)=>a-b);return result;}
export function isUndoShortcut(event){return Boolean((event.ctrlKey||event.metaKey)&&!event.shiftKey&&(event.code==='KeyZ'||String(event.key??'').toLowerCase()==='z'));}
export function isRackRotateShortcut(event){return event?.code==='KeyR';}
export function componentTransform(component){const rotation=((Number(component.rotation)||0)%360+360)%360;return {rotation,scaleX:component.mirrorX?-1:1,scaleY:component.mirrorY?-1:1};}
export function localPointerDelta(dx,dy,rotation=0){const angle=-(Number(rotation)||0)*Math.PI/180,cos=Math.cos(angle),sin=Math.sin(angle);return {x:dx*cos-dy*sin,y:dx*sin+dy*cos};}
export function resizeFromCorner(component,dx,dy,minSize=20){const rotation=componentTransform(component).rotation,local=localPointerDelta(dx,dy,rotation),w=Math.max(minSize,Math.round(component.w+local.x)),h=Math.max(minSize,Math.round(component.h+local.y)),angle=rotation*Math.PI/180,cos=Math.cos(angle),sin=Math.sin(angle),rotate=(x,y)=>({x:x*cos-y*sin,y:x*sin+y*cos}),center={x:component.x+component.w/2,y:component.y+component.h/2},oldHalf=rotate(-component.w/2,-component.h/2),anchor={x:center.x+oldHalf.x,y:center.y+oldHalf.y},newHalf=rotate(w/2,h/2),newCenter={x:anchor.x+newHalf.x,y:anchor.y+newHalf.y};return {x:Math.round(newCenter.x-w/2),y:Math.round(newCenter.y-h/2),w,h};}
const scaledNumber=value=>Math.max(1,Math.round(Number(value)*10)/10);
export function resizeComponentWithContent(component,nextBox){const oldW=Math.max(1,Number(component.w)||1),oldH=Math.max(1,Number(component.h)||1),next={...component,...nextBox},newW=Math.max(1,Number(next.w)||1),newH=Math.max(1,Number(next.h)||1),scale=Math.sqrt(newW/oldW*newH/oldH);if(Number.isFinite(Number(component.size)))next.size=scaledNumber(Number(component.size)*scale);if(Number.isFinite(Number(component.labelSize)))next.labelSize=scaledNumber(Number(component.labelSize)*scale);return next;}
export function scaleComponentFromSize(component,size,minSize=20){const current=Math.max(1,Number(component.size)||1),target=Math.max(1,Number(size)||1),ratio=target/current,cx=Number(component.x)+Number(component.w)/2,cy=Number(component.y)+Number(component.h)/2,w=Math.max(minSize,Math.round(Number(component.w)*ratio)),h=Math.max(minSize,Math.round(Number(component.h)*ratio));return {...component,x:Math.round(cx-w/2),y:Math.round(cy-h/2),w,h,size:target,labelSize:Number.isFinite(Number(component.labelSize))?scaledNumber(Number(component.labelSize)*ratio):component.labelSize};}
const toInches=(value,unit,ppi)=>unit==='px'?Number(value)/Number(ppi):unit==='cm'?Number(value)/2.54:Number(value);
const fromInches=(value,unit,ppi)=>unit==='px'?Number(value)*Number(ppi):unit==='cm'?Number(value)*2.54:Number(value);
const rounded=value=>Number(Number(value).toFixed(4));
export function printPixels(width,height,unit='cm',ppi=300){return {width:Math.max(1,Math.round(fromInches(toInches(width,unit,ppi),'px',ppi))),height:Math.max(1,Math.round(fromInches(toInches(height,unit,ppi),'px',ppi)))};}
export function convertPrintSize(width,height,fromUnit,toUnit,ppi=300){if(fromUnit===toUnit)return {width:Number(width),height:Number(height)};const convert=value=>rounded(fromInches(toInches(value,fromUnit,ppi),toUnit,ppi));return {width:convert(width),height:convert(height)};}
export function unitValueFromPixels(value,unit='px',ppi=300){return rounded(fromInches(Number(value)/Number(ppi),unit,ppi));}
export function unitValueToPixels(value,unit='px',ppi=300){return rounded(fromInches(toInches(value,unit,ppi),'px',ppi));}
export function printPoints(width,height,unit='cm',ppi=300){const convert=value=>rounded(toInches(value,unit,ppi)*72);return {width:convert(width),height:convert(height)};}
export function stackedLabelItems(items,direction='vertical'){return direction==='vertical'?[...items].sort((a,b)=>Number(b.LEVEL)-Number(a.LEVEL)):[...items];}
export function rowNameAt(index){const length=Math.floor(index/26)+1;return 'A'.repeat(length-1)+String.fromCharCode(65+index%26);}
function nextAvailableRow(units){const used=new Set(units.map(u=>u.row));for(let i=0;;i++){const name=rowNameAt(i);if(!used.has(name))return name;}}
export function locations(s){if(s.imported)return s.imported;const out=[];if(Array.isArray(s.units)){for(const u of [...s.units].sort((a,b)=>a.row.localeCompare(b.row)||a.bay-b.bay))for(let l=1;l<=u.levels;l++){const n=u.capacities?.[l]??2;for(const side of n===2?['L','R']:n===1?['S']:[])out.push({PLANT:s.plant,ROW:u.row,BAY:String(u.bay).padStart(2,'0'),LEVEL:String(l),SIDE:side});}return out;}for(const row of s.rows)for(let b=1;b<=row.bays;b++)for(let l=1;l<=bayLevels(row,b);l++){const n=row.cells[`${b}:${l}`]??2;for(const side of n===2?['L','R']:n===1?['S']:[])out.push({PLANT:s.plant,ROW:row.name,BAY:String(b).padStart(2,'0'),LEVEL:String(l),SIDE:side});}return out;}
export function labelGroups(records){const groups=new Map();for(const r of records){const key=`${r.PLANT}_${r.ROW}_${r.BAY}_${r.SIDE}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}return [...groups.entries()].map(([key,items])=>({key,items:items.sort((a,b)=>Number(a.LEVEL)-Number(b.LEVEL))}));}
export function normalize(table){if(!table.length)throw Error('ไฟล์ว่าง');const headers=table[0].map(v=>String(v??'').trim().toUpperCase()),required=['PLANT','ROW','BAY','LEVEL','SIDE'];if(!required.every(h=>headers.includes(h)))throw Error('ต้องมีคอลัมน์ PLANT, ROW, BAY, LEVEL, SIDE');const seen=new Set();return table.slice(1).filter(r=>r.some(v=>String(v??'').trim())).map((r,i)=>{const obj=Object.fromEntries(required.map(h=>[h,String(r[headers.indexOf(h)]??'').trim().toUpperCase()]));if(!/^[A-Z0-9-]+$/.test(obj.PLANT)||!/^[A-Z0-9-]+$/.test(obj.ROW)||!/^\d+$/.test(obj.BAY)||Number(obj.BAY)<1||!/^\d+$/.test(obj.LEVEL)||Number(obj.LEVEL)<1||!['L','R','S'].includes(obj.SIDE))throw Error(`ข้อมูลแถว ${i+2} ไม่ถูกต้อง`);obj.BAY=String(Number(obj.BAY)).padStart(2,'0');obj.LEVEL=String(Number(obj.LEVEL));const key=code(obj);if(seen.has(key))throw Error(`Location ซ้ำ: ${key}`);seen.add(key);return obj;});}
const rack=(id,name,x,y,orientation='horizontal')=>({id,name,bays:4,levels:3,x,y,orientation,bayLevels:{},cells:{}});
export function defaultLabel(){return {template:null,width:900,height:300,printUnit:'cm',printWidth:7.62,printHeight:2.54,ppi:300,levelColors:[...colors],components:[{id:1,type:'color',x:0,y:0,w:900,h:300,fg:'#66cc66',bg:'transparent',auto:true,size:40},{id:2,type:'rect',x:12,y:12,w:876,h:276,fg:'#ffffff',bg:'#ffffff',size:40},{id:3,type:'qr',x:26,y:26,w:248,h:248,fg:'#000000',bg:'#ffffff',size:40},...['PLANT','ROW','BAY','LEVEL','SIDE'].map((type,i)=>({id:i+4,type,x:300+i*108,y:150,w:103,h:105,fg:'#14283f',bg:'transparent',size:38,showLabel:true,labelSize:14})),{id:9,type:'arrow',x:590,y:20,w:170,h:115,fg:'#14283f',bg:'transparent',size:80,auto:true,direction:'↑'}]};}
export function defaultLayout(){return {gridSize:14,units:[{id:101,gx:3,gy:4,axis:'x',direction:0,row:'A',bay:1,levels:3,capacities:{}},{id:102,gx:5,gy:4,axis:'x',direction:0,row:'A',bay:2,levels:3,capacities:{}},{id:103,gx:7,gy:4,axis:'x',direction:0,row:'A',bay:3,levels:3,capacities:{}}],paths:Array.from({length:6},(_,i)=>({gx:3+i,gy:5})),rows:[rack(1,'A',120,150)],aisles:[]};}
export function defaultState(){return {version:7,plant:'ANV1',imported:null,ignoreInvalidRacks:false,...defaultLayout(),...defaultLabel()};}
export function csv(records){return '\ufeffPLANT,ROW,BAY,LEVEL,SIDE,Location_Code\r\n'+records.map(r=>[r.PLANT,r.ROW,r.BAY,r.LEVEL,r.SIDE,code(r)].join(',')).join('\r\n');}
export function subplantRows(records){return records.map(r=>({SubPlant:r.PLANT,RackCode:code(r),TopReserveBy:'',BottomReserveBy:''}));}
export function subplantCsv(records){return '\ufeffSubPlant,RackCode,TopReserveBy,BottomReserveBy\r\n'+subplantRows(records).map(r=>[r.SubPlant,r.RackCode,r.TopReserveBy,r.BottomReserveBy].join(',')).join('\r\n');}
export const exampleRows=[{PLANT:'ANV1',ROW:'A',BAY:'01',LEVEL:'1',SIDE:'L'},{PLANT:'ANV1',ROW:'A',BAY:'01',LEVEL:'1',SIDE:'R'},{PLANT:'ANV1',ROW:'A',BAY:'01',LEVEL:'2',SIDE:'L'},{PLANT:'ANV1',ROW:'A',BAY:'01',LEVEL:'2',SIDE:'R'}];
