import * as THREE from 'three';
import {hasAdjacentPath,rackColumns,rackDirection,unitFootprint,finiteGridCell,zoomTargetCorrection,clampRackZoom} from './model.js';

const C={floor:0x10283b,grid:0x315068,path:0xd0b36a,blue:0x086fe3,blueTop:0x1888ff,darkBlue:0x043f94,orange:0xff8315,silver:0xdce5eb,yellow:0xffe21b,black:0x202020,red:0xd93b3b,gold:0xf4bd3f,teal:0x52d8c8};
const material=(color,extra={})=>new THREE.MeshStandardMaterial({color,roughness:.62,metalness:.18,...extra});
const materials={
  normal:{post:material(C.blue,{metalness:.45}),bin:material(C.blue),lid:material(C.blueTop),beam:material(C.orange,{metalness:.3}),brace:material(C.silver,{metalness:.75}),guard:material(C.yellow),stripe:material(C.black),plate:material(C.blue,{metalness:.5})},
  active:{post:material(C.gold),bin:material(0xe4a92f),lid:material(0xffd765),beam:material(0xffa528),brace:material(0xffefbc),guard:material(0xffed75),stripe:material(C.black),plate:material(C.gold)},
  invalid:{post:material(C.red),bin:material(0xb92727),lid:material(0xff6262),beam:material(0x8f1f1f),brace:material(0xffb0b0),guard:material(0xff6666),stripe:material(0x651111),plate:material(C.red)},
  erase:{post:material(0xff922b),bin:material(0xff7b16),lid:material(0xffbd78),beam:material(0xff5f00),brace:material(0xffe0c2),guard:material(0xff922b),stripe:material(0x8f3900),plate:material(0xff922b)},
  preview:{post:material(C.teal,{transparent:true,opacity:.5}),bin:material(0x43b9ad,{transparent:true,opacity:.5}),lid:material(0x86f2e5,{transparent:true,opacity:.5}),beam:material(0xf3cf72,{transparent:true,opacity:.5}),brace:material(0xe7fffb,{transparent:true,opacity:.5}),guard:material(0xfff09b,{transparent:true,opacity:.5}),stripe:material(0xffffff,{transparent:true,opacity:.45}),plate:material(C.teal,{transparent:true,opacity:.5})}
};
const sceneMaterials={floor:material(C.floor),path:material(C.path),pathActive:material(0xffe08a),pathErase:material(0xff922b),pathPreview:material(0xffe095,{transparent:true,opacity:.5})};
const selectionMaterial=new THREE.MeshBasicMaterial({color:C.teal,transparent:true,opacity:.2,depthWrite:false,side:THREE.DoubleSide}),selectionEdgeMaterial=new THREE.LineBasicMaterial({color:0x7ffbea,transparent:true,opacity:.95});
const box=(w,h,d,role)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),materials.normal[role]);mesh.userData.role=role;mesh.castShadow=true;mesh.receiveShadow=true;return mesh;};
function addBox(group,w,h,d,x,y,z,role){const mesh=box(w,h,d,role);mesh.position.set(x,y,z);group.add(mesh);return mesh;}
function brace(group,a,b){const start=new THREE.Vector3(...a),end=new THREE.Vector3(...b),delta=end.clone().sub(start),mesh=new THREE.Mesh(new THREE.CylinderGeometry(.025,.025,delta.length(),8),materials.normal.brace);mesh.userData.role='brace';mesh.position.copy(start).add(end).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),delta.normalize());group.add(mesh);}
function taperedBinGeometry(topWidth,bottomWidth,height,depth){const tw=topWidth/2,bw=bottomWidth/2,d=depth/2,y=height/2,v=[-bw,-y,-d,bw,-y,-d,bw,-y,d,-bw,-y,d,-tw,y,-d,tw,y,-d,tw,y,d,-tw,y,d],indices=[0,1,5,0,5,4,1,2,6,1,6,5,2,3,7,2,7,6,3,0,4,3,4,7,4,5,6,4,6,7,0,3,2,0,2,1],g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(v,3));g.setIndex(indices);g.computeVertexNormals();return g;}
function addBin(group,x,y,width){const height=.64,depth=.64,body=new THREE.Mesh(taperedBinGeometry(width,width*.8,height,depth),materials.normal.bin);body.userData.role='bin';body.position.set(x,y+.22,0);body.castShadow=true;group.add(body);addBox(group,width+.04,.08,depth+.04,x,y+.58,0,'lid');for(const offset of [-.3,0,.3])addBox(group,width*.15,.1,depth*.72,x+offset*width,y-.15,0,'bin');}
function addGuard(group,x,z){addBox(group,.16,.36,.16,x,.2,z,'guard');for(const y of [.1,.22,.34]){const stripe=addBox(group,.17,.045,.171,x,y,z,'stripe');stripe.rotation.z=.35;}}
function addLabel(group,text,height){const canvas=document.createElement('canvas');canvas.width=256;canvas.height=64;const context=canvas.getContext('2d');context.fillStyle='#0d2940';context.fillRect(2,2,252,60);context.strokeStyle='#8eeadd';context.lineWidth=4;context.strokeRect(2,2,252,60);context.fillStyle='#ffffff';context.font='700 34px system-ui';context.textAlign='center';context.textBaseline='middle';context.fillText(text,128,33);const texture=new THREE.CanvasTexture(canvas),sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:texture,transparent:true,depthTest:true}));sprite.position.set(0,height+.18,0);sprite.scale.set(1.25,.31,1);group.add(sprite);}
function rackGroup(unit,stateName='normal'){
  const columns=rackColumns(unit),levels=Math.max(1,Number(unit.levels)||1),width=columns===2?1.82:.86,depth=.82,height=levels*.82+.42,group=new THREE.Group();group.userData.unitId=unit.id;
  for(const x of [-width/2,width/2])for(const z of [-depth/2,depth/2]){addBox(group,.09,height,.09,x,height/2,z,'post');addBox(group,.18,.04,.18,x,.02,z,'plate');}
  for(const z of [-depth/2,depth/2])addBox(group,width,.13,.1,0,.16,z,'beam');
  for(const x of [-width/2,width/2]){brace(group,[x,.22,-depth/2],[x,height-.16,depth/2]);brace(group,[x,.22,depth/2],[x,height-.16,-depth/2]);}
  for(let level=1;level<=levels;level++){const capacity=Number(unit.capacities?.[level]??2);if(capacity===2){addBin(group,-.46,.35+(level-1)*.82,.78);addBin(group,.46,.35+(level-1)*.82,.78);}else if(capacity===1)addBin(group,0,.35+(level-1)*.82,.78);}
  for(const x of [-width/2,width/2])for(const z of [-depth/2,depth/2])addGuard(group,x,z);
  if(unit.id!=='preview')addLabel(group,`${unit.row}-${String(unit.bay).padStart(2,'0')}`,height);
  group.rotation.y=rackDirection(unit)*Math.PI/2;
  const cells=unitFootprint(unit),center=cells.reduce((sum,c)=>({x:sum.x+c.gx+.5,z:sum.z+c.gy+.5}),{x:0,z:0});group.position.set(center.x/cells.length,0,center.z/cells.length);applyRackState(group,stateName);return group;
}
function applyRackState(group,name){const set=materials[name]??materials.normal;group.traverse(object=>{if(object.isMesh&&object.userData.role)object.material=set[object.userData.role]??set.bin;});}
function disposeObject(root){root.traverse(object=>{if(object.geometry)object.geometry.dispose();if(object.isSprite){object.material.map?.dispose();object.material.dispose();}});}

export function createRackScene(container,{state,view='iso',rotation=0,zoom=1,cameraState={},onCameraChange=()=>{},selectedUnits=[],selectedPaths=[]}){
  const scene=new THREE.Scene();scene.background=new THREE.Color(C.floor);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;container.replaceChildren(renderer.domElement);
  const camera=new THREE.OrthographicCamera(),center=state.gridSize/2,root=new THREE.Group(),previewRoot=new THREE.Group(),selectionRoot=new THREE.Group();scene.add(root,previewRoot,selectionRoot,new THREE.HemisphereLight(0xd9f5ff,0x183342,2.2));const sun=new THREE.DirectionalLight(0xffffff,2.8);sun.position.set(-8,16,-6);sun.castShadow=true;scene.add(sun);
  const floor=new THREE.Mesh(new THREE.PlaneGeometry(state.gridSize,state.gridSize),sceneMaterials.floor);floor.rotation.x=-Math.PI/2;floor.position.set(center,-.03,center);floor.receiveShadow=true;floor.userData.floor=true;root.add(floor);const grid=new THREE.GridHelper(state.gridSize,state.gridSize,C.grid,C.grid);grid.position.set(center,0,center);root.add(grid);
  const unitGroups=new Map(),pathMeshes=new Map(),selectedSet=new Set(selectedUnits),selectedPathSet=new Set(selectedPaths);
  for(const path of state.paths){const key=`${path.gx},${path.gy}`,mesh=addBox(root,.94,.05,.94,path.gx+.5,.015,path.gy+.5,'beam');mesh.material=selectedPathSet.has(key)?sceneMaterials.pathActive:sceneMaterials.path;mesh.userData.pathKey=key;pathMeshes.set(key,mesh);}
  for(const unit of state.units){const status=selectedSet.has(unit.id)?'active':hasAdjacentPath(unit,state.paths)?'normal':'invalid',group=rackGroup(unit,status);root.add(group);unitGroups.set(unit.id,group);}
  cameraState.targetX=Number.isFinite(cameraState.targetX)?cameraState.targetX:center;cameraState.targetZ=Number.isFinite(cameraState.targetZ)?cameraState.targetZ:center;cameraState.zoom=clampRackZoom(cameraState.zoom??zoom);
  function configureCamera(){const w=Math.max(1,container.clientWidth),h=Math.max(1,container.clientHeight),aspect=w/h,size=(state.gridSize+4)/cameraState.zoom,targetX=cameraState.targetX,targetZ=cameraState.targetZ;camera.left=-size*aspect/2;camera.right=size*aspect/2;camera.top=size/2;camera.bottom=-size/2;camera.near=.1;camera.far=200;if(view==='top'){camera.position.set(targetX,40,targetZ);const ups=[[0,0,-1],[-1,0,0],[0,0,1],[1,0,0]][rotation];camera.up.set(...ups);}else{const angle=(45+rotation*90)*Math.PI/180,d=28;camera.position.set(targetX+Math.cos(angle)*d,20,targetZ+Math.sin(angle)*d);camera.up.set(0,1,0);}camera.lookAt(targetX,0,targetZ);camera.updateProjectionMatrix();renderer.setSize(w,h,false);renderer.render(scene,camera);}
  const observer=new ResizeObserver(configureCamera);observer.observe(container);configureCamera();
  const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0),intersection=new THREE.Vector3();
  function setRay(event){const bounds=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-bounds.left)/bounds.width*2-1,-((event.clientY-bounds.top)/bounds.height)*2+1);raycaster.setFromCamera(pointer,camera);}
  function floorPointFromEvent(event){setRay(event);if(!raycaster.ray.intersectPlane(plane,intersection))return null;return {x:intersection.x,z:intersection.z};}
  function gridFromEvent(event){const point=floorPointFromEvent(event);return point?finiteGridCell({gx:point.x,gy:point.z},state.gridSize):null;}
  function hitFromEvent(event){setRay(event);for(const hit of raycaster.intersectObjects(root.children,true)){let object=hit.object;while(object){if(object.userData.unitId!=null)return {unitId:object.userData.unitId};if(object.userData.pathKey)return {pathKey:object.userData.pathKey};object=object.parent;}}return {};}
  function setSelection(unitIds,pathKeys){const units=new Set(unitIds),paths=new Set(pathKeys);for(const unit of state.units)applyRackState(unitGroups.get(unit.id),units.has(unit.id)?'active':hasAdjacentPath(unit,state.paths)?'normal':'invalid');for(const [key,mesh] of pathMeshes)mesh.material=paths.has(key)?sceneMaterials.pathActive:sceneMaterials.path;renderer.render(scene,camera);}
  function setErase(unitIds,pathKeys){for(const unit of state.units)applyRackState(unitGroups.get(unit.id),unitIds.has(unit.id)?'erase':selectedSet.has(unit.id)?'active':hasAdjacentPath(unit,state.paths)?'normal':'invalid');for(const [key,mesh] of pathMeshes)mesh.material=pathKeys.has(key)?sceneMaterials.pathErase:selectedPathSet.has(key)?sceneMaterials.pathActive:sceneMaterials.path;renderer.render(scene,camera);}
  function setPreview(kind,points,{axis='x',capacity=2}={}){disposeObject(previewRoot);previewRoot.clear();for(const point of points){if(kind==='path'){const mesh=addBox(previewRoot,.94,.055,.94,point.gx+.5,.02,point.gy+.5,'beam');mesh.material=sceneMaterials.pathPreview;}else{const direction=axis==='y'?1:0,ghost=rackGroup({id:'preview',gx:point.gx,gy:point.gy,axis,direction,row:'',bay:0,levels:3,capacities:{1:capacity,2:capacity,3:capacity}},'preview');previewRoot.add(ghost);}}renderer.render(scene,camera);}
  function setSelectionBox(from,to){disposeObject(selectionRoot);selectionRoot.clear();if(!from||!to){renderer.render(scene,camera);return;}const minX=Math.min(from.gx,to.gx),maxX=Math.max(from.gx,to.gx)+1,minZ=Math.min(from.gy,to.gy),maxZ=Math.max(from.gy,to.gy)+1,w=maxX-minX,d=maxZ-minZ,geometry=new THREE.PlaneGeometry(w,d),fill=new THREE.Mesh(geometry,selectionMaterial);fill.rotation.x=-Math.PI/2;fill.position.set(minX+w/2,.035,minZ+d/2);selectionRoot.add(fill);const edge=new THREE.LineSegments(new THREE.EdgesGeometry(new THREE.BoxGeometry(w,.03,d)),selectionEdgeMaterial);edge.position.set(minX+w/2,.05,minZ+d/2);selectionRoot.add(edge);renderer.render(scene,camera);}
  function clearSelectionBox(){setSelectionBox(null,null);}
  function setMovePreview(plan){disposeObject(previewRoot);previewRoot.clear();if(!plan){renderer.render(scene,camera);return;}const stateName=plan.valid?'preview':'invalid';for(const unit of plan.units){const ghost=rackGroup({...unit,id:'preview'},stateName);previewRoot.add(ghost);}for(const path of plan.paths){const mesh=addBox(previewRoot,.94,.055,.94,path.gx+.5,.02,path.gy+.5,'beam');mesh.material=plan.valid?sceneMaterials.pathPreview:sceneMaterials.pathErase;}renderer.render(scene,camera);}
  function clearMovePreview(){setMovePreview(null);}
  function reportCamera(){onCameraChange({...cameraState});}
  function setZoom(next,event){const before=event?floorPointFromEvent(event):null;cameraState.zoom=clampRackZoom(next);configureCamera();if(before){const after=floorPointFromEvent(event);if(after){const correction=zoomTargetCorrection(before,after);cameraState.targetX+=correction.x;cameraState.targetZ+=correction.z;configureCamera();}}reportCamera();}
  function fitCamera(){cameraState.targetX=center;cameraState.targetZ=center;cameraState.zoom=1;configureCamera();reportCamera();}
  const wheel=event=>{event.preventDefault();setZoom(cameraState.zoom*Math.exp(-event.deltaY*.0015),event);};renderer.domElement.addEventListener('wheel',wheel,{passive:false});
  let panning=false,panPoint=null;
  const panStart=event=>{if(event.button!==1)return;event.preventDefault();event.stopPropagation();panning=true;panPoint=floorPointFromEvent(event);renderer.domElement.setPointerCapture(event.pointerId);};
  const panMove=event=>{if(!panning||!panPoint)return;event.preventDefault();event.stopPropagation();const current=floorPointFromEvent(event);if(!current)return;cameraState.targetX+=panPoint.x-current.x;cameraState.targetZ+=panPoint.z-current.z;configureCamera();panPoint=floorPointFromEvent(event);reportCamera();};
  const panEnd=event=>{if(!panning)return;event.preventDefault();event.stopPropagation();panning=false;panPoint=null;};
  renderer.domElement.addEventListener('pointerdown',panStart);renderer.domElement.addEventListener('pointermove',panMove);renderer.domElement.addEventListener('pointerup',panEnd);renderer.domElement.addEventListener('pointercancel',panEnd);renderer.domElement.addEventListener('auxclick',event=>{if(event.button===1)event.preventDefault();});
  function dispose(){observer.disconnect();renderer.domElement.removeEventListener('wheel',wheel);renderer.domElement.removeEventListener('pointerdown',panStart);renderer.domElement.removeEventListener('pointermove',panMove);renderer.domElement.removeEventListener('pointerup',panEnd);renderer.domElement.removeEventListener('pointercancel',panEnd);disposeObject(scene);renderer.dispose();renderer.forceContextLoss();renderer.domElement.remove();}
  return {gridFromEvent,hitFromEvent,setSelection,setErase,setPreview,setSelectionBox,clearSelectionBox,setMovePreview,clearMovePreview,setZoom,fitCamera,dispose,canvas:renderer.domElement};
}
